{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.11.0.aar",
          "url": "livekit-android-camerax-2.11.0.aar",
          "size": 40735,
          "sha512": "b74a2f6820a93d7a745ab71d438bb6a9feefbde86c7c32e40d0e1a8bfc301cdd4ed4560ad484c3f2388878fcc35f50a2f0031f414da264f6dfedaf00e5dc0920",
          "sha256": "6d6a23eeaea2c3395045811fc97254207194023cc824abf8456a22d63a2265f6",
          "sha1": "54f02f1fb9843b50d956f1b6604e49a4cf1e23fc",
          "md5": "7232e7ca12036622cc52872a1d40616b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.11.0.aar",
          "url": "livekit-android-camerax-2.11.0.aar",
          "size": 40735,
          "sha512": "b74a2f6820a93d7a745ab71d438bb6a9feefbde86c7c32e40d0e1a8bfc301cdd4ed4560ad484c3f2388878fcc35f50a2f0031f414da264f6dfedaf00e5dc0920",
          "sha256": "6d6a23eeaea2c3395045811fc97254207194023cc824abf8456a22d63a2265f6",
          "sha1": "54f02f1fb9843b50d956f1b6604e49a4cf1e23fc",
          "md5": "7232e7ca12036622cc52872a1d40616b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.11.0-sources.jar",
          "url": "livekit-android-camerax-2.11.0-sources.jar",
          "size": 21611,
          "sha512": "7433f06063e19ba2a6a31bfdf282688faa2a73ae74dcc1062f5389828302161128fef8b39e95af44379e91d48934efde1071bad09d03b6561f45adea47961052",
          "sha256": "463f03522b38d4a30ac433a0cd5e3348588f02d2c8a32605fd0fd57277042a57",
          "sha1": "164ca091589dfb54af91cf2f16a4a48978baadcc",
          "md5": "55686839cd8147d073c1c5419428eaea"
        }
      ]
    }
  ]
}
