{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "ttsignal",
    "version": "2.24.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ttsignal-2.24.1.10.aar",
          "url": "ttsignal-2.24.1.10.aar",
          "size": 3053087,
          "sha512": "237d1f4bc15cf7a90ae97ba49084b1cf5700be37fcf91cb3557b5c3bedab80e853d716b5217ad0cc3384b9dd6fca0b1e9b6dfb3c4a2c2803663e1bf6215da1a8",
          "sha256": "8163f28644556791a76dac26ab8b432ccb96d76d14a466ee0c13465ad5d518c1",
          "sha1": "58352f064da5a66531df6d764c96d93992a27713",
          "md5": "436f8d502101b067a2974d28e312e377"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-2.24.1.10.aar",
          "url": "ttsignal-2.24.1.10.aar",
          "size": 3053087,
          "sha512": "237d1f4bc15cf7a90ae97ba49084b1cf5700be37fcf91cb3557b5c3bedab80e853d716b5217ad0cc3384b9dd6fca0b1e9b6dfb3c4a2c2803663e1bf6215da1a8",
          "sha256": "8163f28644556791a76dac26ab8b432ccb96d76d14a466ee0c13465ad5d518c1",
          "sha1": "58352f064da5a66531df6d764c96d93992a27713",
          "md5": "436f8d502101b067a2974d28e312e377"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-2.24.1.10-sources.jar",
          "url": "ttsignal-2.24.1.10-sources.jar",
          "size": 6375,
          "sha512": "4aac30ce952502e088edfeab02b353468158f146f4637259691f15a9b9b0516ce12193fdbcfb4c78cd0fdb52ebd7cddf39813a7becebcb4f0186e6817d9cce42",
          "sha256": "19e20edcfd3791837cfa06954609c717682d7624840b5efbe136cedcd62e9ebf",
          "sha1": "d39723ad1a8b5b9c51ee50ce2928598e646de8ea",
          "md5": "47be20c9aacdc9e6f911ac134f2ac6d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-2.24.1.10-javadoc.jar",
          "url": "ttsignal-2.24.1.10-javadoc.jar",
          "size": 301549,
          "sha512": "d75c65cf11f48da6d135a6f7173dc17bf0beaab543dfffc5b65574900052e6d7d31db526e40bfc9b80c2efa8a68af29f33814dd1e877f98685dd1edd3d80e91f",
          "sha256": "fd9e1307cc80db0597bcc3b07ed472db8d03a257d54a39ec1cd0fb7682427fd5",
          "sha1": "3ef5dbb25e1df1cb9b7c85c116e8ab53ca277143",
          "md5": "c21f063a3bd9e38cee346a6f2baded32"
        }
      ]
    }
  ]
}
