{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.27.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.6.aar",
          "url": "livekit-android-2.27.0.6.aar",
          "size": 2888429,
          "sha512": "744f2c29c665254bcbe008db0b9dc988f01a2b3070722716823136aaaaef6fe4846002712fa32083802eb5f33f7e03586adc35ccc69fd4c3dceff61d84a7be3d",
          "sha256": "4d833a3a3214e2258199c1e0321aaa424812c6673a6b54e03cfa4c999be28a28",
          "sha1": "7335ffb7643498ad9fbaad54f4546930ca5577b6",
          "md5": "026b29ab0b68664336f144abfb87cb67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.27.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.6.aar",
          "url": "livekit-android-2.27.0.6.aar",
          "size": 2888429,
          "sha512": "744f2c29c665254bcbe008db0b9dc988f01a2b3070722716823136aaaaef6fe4846002712fa32083802eb5f33f7e03586adc35ccc69fd4c3dceff61d84a7be3d",
          "sha256": "4d833a3a3214e2258199c1e0321aaa424812c6673a6b54e03cfa4c999be28a28",
          "sha1": "7335ffb7643498ad9fbaad54f4546930ca5577b6",
          "md5": "026b29ab0b68664336f144abfb87cb67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.6-sources.jar",
          "url": "livekit-android-2.27.0.6-sources.jar",
          "size": 647178,
          "sha512": "04fef1bf5ad9374736af6381082ec86866bb3d837ec8101d0ed23bc3bc71039d6bf4e6ce05c2ac4ee7baeeb927ad690121eeea0b05fadb2d98c0abfec1756e9a",
          "sha256": "0a5c20e2e2d61c20f174b56e4ac88da245fc52059e05bf21a89229c7a74865d9",
          "sha1": "4625fe690af8041d80d16655c2c41940b546e77c",
          "md5": "6a8ac1166b5ffec92fa4280f639302a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.6-javadoc.jar",
          "url": "livekit-android-2.27.0.6-javadoc.jar",
          "size": 4127305,
          "sha512": "6dcc1f24cd94664f189275a843f466e8ec6deb2428102b2017de6eb0b4ffc08902258375269a47928a9ec003eb38073365e948d76be0d9760d669566ab9fecad",
          "sha256": "494807f06e649f299a7a8df6231064b25ea20dfcd2fa30dfe3eba8c97cd3fcab",
          "sha1": "e08ab37b8156c799c70d661a1c005f7281c4b699",
          "md5": "1c7df474d644804e482e63c997932c78"
        }
      ]
    }
  ]
}
