{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.2.aar",
          "url": "livekit-android-2.20.3.2.aar",
          "size": 3617115,
          "sha512": "008bd41e151f10b8bba93696fde78232fde3e2d882717137f651c625561a178e0b00e8d77281efb48b180b12108dfe4664cd2acb1fbe8322f5e33928e8070e18",
          "sha256": "3657138cd12fe2f51e0cb41ea9bf49a36181bf047a6d6103ca68f7c73a36fdce",
          "sha1": "c020140fca10a734056c13c9ca0b4359e7159c48",
          "md5": "34b8d90484a6d72bc9c8b1c75b529f38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.2.aar",
          "url": "livekit-android-2.20.3.2.aar",
          "size": 3617115,
          "sha512": "008bd41e151f10b8bba93696fde78232fde3e2d882717137f651c625561a178e0b00e8d77281efb48b180b12108dfe4664cd2acb1fbe8322f5e33928e8070e18",
          "sha256": "3657138cd12fe2f51e0cb41ea9bf49a36181bf047a6d6103ca68f7c73a36fdce",
          "sha1": "c020140fca10a734056c13c9ca0b4359e7159c48",
          "md5": "34b8d90484a6d72bc9c8b1c75b529f38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.2-sources.jar",
          "url": "livekit-android-2.20.3.2-sources.jar",
          "size": 921674,
          "sha512": "43338628f24b25653b9c079daaeb23c5658bf16b8225944bd2ff89773d64a3a2d62b468bbf96b1a03c013b618e2b1e424b3f4aaaa54a89c43df1e3e8321f9657",
          "sha256": "c3f6225254d3f42d8db9d4be5cae83501e560a0e74046858d078346f35e16bd4",
          "sha1": "503e5b8cfbb2860509adda1eacba1ded24180c51",
          "md5": "1e9be7662a17f7991384997c08d195f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.2-javadoc.jar",
          "url": "livekit-android-2.20.3.2-javadoc.jar",
          "size": 6838968,
          "sha512": "df6201e4afc58236d59c4d52676d6c28b5c7770fafb7ee7baff281e13d6947855551257c88bf367978cef991774107bc5fb5fc06b30141fa8cf816086c5af299",
          "sha256": "9f130cf34f0f9d2096e0cd3862b7b0e313b73b41ef312d8fdd2063cc95cb8dbf",
          "sha1": "1ed0eb172db2af6bbc1360061b151446cd4310a6",
          "md5": "170f3104b1c13a0af3483b41b91528a9"
        }
      ]
    }
  ]
}
