{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.13.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.2.aar",
          "url": "livekit-android-2.13.1.2.aar",
          "size": 2939799,
          "sha512": "45ddb4879af2fdad39aa03ac8d2199a03135e89045804d3f63bfdb21510284eeb6afe5b6589f75a37299a0228648987d52ace97cc2e952f702e090c527c0b2ce",
          "sha256": "02c1e0d160ab06adc984bef8f9028cd82267038c7faf0fe04d80004f7dede155",
          "sha1": "42c04bcbb4a361cfe1b466120f6b2bc594bc4388",
          "md5": "94bc7d47416a1771647067c69e921ebf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.2.aar",
          "url": "livekit-android-2.13.1.2.aar",
          "size": 2939799,
          "sha512": "45ddb4879af2fdad39aa03ac8d2199a03135e89045804d3f63bfdb21510284eeb6afe5b6589f75a37299a0228648987d52ace97cc2e952f702e090c527c0b2ce",
          "sha256": "02c1e0d160ab06adc984bef8f9028cd82267038c7faf0fe04d80004f7dede155",
          "sha1": "42c04bcbb4a361cfe1b466120f6b2bc594bc4388",
          "md5": "94bc7d47416a1771647067c69e921ebf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.2-sources.jar",
          "url": "livekit-android-2.13.1.2-sources.jar",
          "size": 778679,
          "sha512": "71945378bf62fdc311ca3223cc5cfabea40144cbbff44ce12767b4bd43403b1177ed103159605bbae2742382583fbe129cd73a624b34a30da3f7096da4b8a047",
          "sha256": "aecf4c944c86f7d44b370a664e829aa2c5c2acf4aefbab221cc5e8945d4a01d9",
          "sha1": "ae6e1d884e639a50f49f0981c135a07cfa004c35",
          "md5": "c83562004d1ad5a0f2aabd745ac31636"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.2-javadoc.jar",
          "url": "livekit-android-2.13.1.2-javadoc.jar",
          "size": 5757501,
          "sha512": "afae0c62cab985b82dc0c21777d5bc24a4addec1c4596a4a3f94ed5be084b54382c5d4965146022f1c83c82b1bc635ae4b0e5132f3482229bf20a0b111f2cc8b",
          "sha256": "2e18a3004a88c888526b954b3b94d5b970c9defd8789e1c7e9eafad825d61333",
          "sha1": "3cbff6bc7ed338ad5474564e9bba07d08fc4e349",
          "md5": "945b0aa963d60f23b30ea6e72d72010d"
        }
      ]
    }
  ]
}
