{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.13.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.1.aar",
          "url": "livekit-android-camerax-2.13.1.1.aar",
          "size": 40875,
          "sha512": "a6c56d8f51bd26f3e034114a0ab3864c688e5f88da7ff0e0594b58950e674d9c6dcc83c96fc098b3e5ddb6ff4f71ef942aafd7156df3c9e8b15a035adbb4dc37",
          "sha256": "41f67a875c5207182f8bbcb505373fb76e8031cb5df3a2b9ba64c9632f8db33a",
          "sha1": "12e1733fd2c3cf669ef283d2c4ae63f5cbb5a631",
          "md5": "6f41de54b6450a3e21078936249f0169"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.13.1.1"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.1.aar",
          "url": "livekit-android-camerax-2.13.1.1.aar",
          "size": 40875,
          "sha512": "a6c56d8f51bd26f3e034114a0ab3864c688e5f88da7ff0e0594b58950e674d9c6dcc83c96fc098b3e5ddb6ff4f71ef942aafd7156df3c9e8b15a035adbb4dc37",
          "sha256": "41f67a875c5207182f8bbcb505373fb76e8031cb5df3a2b9ba64c9632f8db33a",
          "sha1": "12e1733fd2c3cf669ef283d2c4ae63f5cbb5a631",
          "md5": "6f41de54b6450a3e21078936249f0169"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.1-sources.jar",
          "url": "livekit-android-camerax-2.13.1.1-sources.jar",
          "size": 21733,
          "sha512": "752e3369d79c198e335859e9d886a7a3726ab8ef2d1b198f019e571b3d7d9abe89fd137295f354005f02b11635d4636ab3a24a2c4c125c62e6d041017e68a77e",
          "sha256": "ce95d94abc7136fafc7256b0d7936802039b0f100c64c3fa147939a2ac6065de",
          "sha1": "84993b47535d8f41d644e389543a6d1de4753fa3",
          "md5": "3695f3492b086eb267300c03ef4061dd"
        }
      ]
    }
  ]
}
