{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.22.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.1.aar",
          "url": "livekit-android-2.22.0.1.aar",
          "size": 3938370,
          "sha512": "ca8be2e049c4872a2e8ab9ac0495c9a0663aae318003b8e6fb46214800680fa9eb45c05ee510d410c6b9b5be97f8388820c04cea958e21872193962da1b44d1d",
          "sha256": "509c2b4dad03cd5a0f568ca2e0c435c2938375ecb81d02e6bfbbb1a4eba0c8b3",
          "sha1": "dc48c6121f00125cecdfbaf40e98fbf03fc96b29",
          "md5": "68461918e8e1bd346db6ed754fb93d91"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.1.aar",
          "url": "livekit-android-2.22.0.1.aar",
          "size": 3938370,
          "sha512": "ca8be2e049c4872a2e8ab9ac0495c9a0663aae318003b8e6fb46214800680fa9eb45c05ee510d410c6b9b5be97f8388820c04cea958e21872193962da1b44d1d",
          "sha256": "509c2b4dad03cd5a0f568ca2e0c435c2938375ecb81d02e6bfbbb1a4eba0c8b3",
          "sha1": "dc48c6121f00125cecdfbaf40e98fbf03fc96b29",
          "md5": "68461918e8e1bd346db6ed754fb93d91"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0.1-sources.jar",
          "url": "livekit-android-2.22.0.1-sources.jar",
          "size": 1000269,
          "sha512": "576dd09e7319e5a458d203a6edf3508d8e3a3ce62182e9b03969b37f7ac2e402006ba5560f25f958e94302ba1962271e44ba599426b2709d3c8a12a813d278fd",
          "sha256": "dba1b30816c798bf6223edf5dfa4be8f7a1d7b7fb653401bf970814e17286d75",
          "sha1": "d75e4fb485fa06124c1283bff2ebb634de2a429c",
          "md5": "bd151df4ca70e084613047cb80ecc62b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0.1-javadoc.jar",
          "url": "livekit-android-2.22.0.1-javadoc.jar",
          "size": 7447686,
          "sha512": "fe7b8ea68427f5583be47648381cf2f1e1b593a39a2ccb5bee01f3693df4ecbd40f18db99e7db612b78f9c4d6c75f4b8b556101c3b4b1a4b01785659476256d9",
          "sha256": "cab8e2a78be457c78017399c9f95f038ab0099a69c9cfd3e1900e46b3ff844d2",
          "sha1": "0d4b42dacf9071f23d106dc10cb24e60545454a1",
          "md5": "43e00e2afaedbd0c45266dfdfa201724"
        }
      ]
    }
  ]
}
