{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "rust-encryption-sdk",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "rust-encryption-sdk-0.1.4.aar",
          "url": "rust-encryption-sdk-0.1.4.aar",
          "size": 681891,
          "sha512": "91fbd67ba6c2c02fd849bd6c391b4cd328ae0166e3cfb1d7761a9c6d22fa3e8e88e06e7ee7484836ba2d1507e57ec1fb33dac2713b8692541724056f06b6160a",
          "sha256": "7c39593ef2820f34200fe666c881052cbeaa3435ddcdec2e5fe8bdc31dea11e6",
          "sha1": "4f56662da9d8065dfe6bc5bfe5e17b3be5dee3a6",
          "md5": "cf60f90b72c0143578d83ca8dbf079d1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "rust-encryption-sdk-0.1.4.aar",
          "url": "rust-encryption-sdk-0.1.4.aar",
          "size": 681891,
          "sha512": "91fbd67ba6c2c02fd849bd6c391b4cd328ae0166e3cfb1d7761a9c6d22fa3e8e88e06e7ee7484836ba2d1507e57ec1fb33dac2713b8692541724056f06b6160a",
          "sha256": "7c39593ef2820f34200fe666c881052cbeaa3435ddcdec2e5fe8bdc31dea11e6",
          "sha1": "4f56662da9d8065dfe6bc5bfe5e17b3be5dee3a6",
          "md5": "cf60f90b72c0143578d83ca8dbf079d1"
        }
      ]
    }
  ]
}
