{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.13.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.5.aar",
          "url": "livekit-android-2.13.1.5.aar",
          "size": 2939829,
          "sha512": "be2f8b4c4754a17f22afae4f1a670538447dffb969d9e60cd34d88665b69094ea6e0922c5ffd0f1693e081417c7fb95ec4f34179d7940166eaf135a2fd853f48",
          "sha256": "cd5a14b098247869a598dd41d615da647d74e7c3390e6e1589c1abb900971f11",
          "sha1": "e1c9f1965d7d66ebcabe8364ab3e1f8a45a4c138",
          "md5": "9ea3b0386b082126a33ade413292fbc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.5.aar",
          "url": "livekit-android-2.13.1.5.aar",
          "size": 2939829,
          "sha512": "be2f8b4c4754a17f22afae4f1a670538447dffb969d9e60cd34d88665b69094ea6e0922c5ffd0f1693e081417c7fb95ec4f34179d7940166eaf135a2fd853f48",
          "sha256": "cd5a14b098247869a598dd41d615da647d74e7c3390e6e1589c1abb900971f11",
          "sha1": "e1c9f1965d7d66ebcabe8364ab3e1f8a45a4c138",
          "md5": "9ea3b0386b082126a33ade413292fbc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.5-sources.jar",
          "url": "livekit-android-2.13.1.5-sources.jar",
          "size": 778761,
          "sha512": "80dd6e31f1d98d79af66f3312e8b079aeb46ef9dae7d7cea778c0c64a8bf56a603b00fa76e7229e73be88b366a27ca263fee96d7fc2aaa6520e8411cde48e0f9",
          "sha256": "f2c2d8fd9cc2032762ca220d1af60a1793a4f19ecca19edc48fdc55bb5f2468b",
          "sha1": "fe8f0f32e6a3b4cff076f76e95df7c5d6b144242",
          "md5": "34d9519ea88b74e3878a4cff55afd43d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.5-javadoc.jar",
          "url": "livekit-android-2.13.1.5-javadoc.jar",
          "size": 5757898,
          "sha512": "e875f3ad42209409daddd4089e4da3b8a95ca4f06324165ba2e72b2d04c34af709b5f27e20449b0397e635b2922a96caf44d22060a081d5ef4416e2c2946dd56",
          "sha256": "f0027447d950a88e22aaad5958f02014d1d2b2f9201f03b2f2cd2c3299e3ca47",
          "sha1": "77d2598e5c07f1d39517292890899a97961306b0",
          "md5": "4cdd4ab096ff91df69d14a775a58726d"
        }
      ]
    }
  ]
}
