{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.aar",
          "url": "livekit-android-2.20.3.aar",
          "size": 3611434,
          "sha512": "ea43ff8d0e1784d6ed9568863d4fcb676cf327f58c1005b5ccb12934eb07ded1263bc71be1e4f63eee04119bed0e22ac68ddaf3aa4e6c4e9a5ec132d8f224c79",
          "sha256": "a56f6bc2816c00611b87b7e2103f202ef0b81a4db738688514ca956515a41020",
          "sha1": "a06d5c51d036530835739f096196b9c8b7a2b39b",
          "md5": "81b5e848f58587ba9d4f188bda2e39a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.aar",
          "url": "livekit-android-2.20.3.aar",
          "size": 3611434,
          "sha512": "ea43ff8d0e1784d6ed9568863d4fcb676cf327f58c1005b5ccb12934eb07ded1263bc71be1e4f63eee04119bed0e22ac68ddaf3aa4e6c4e9a5ec132d8f224c79",
          "sha256": "a56f6bc2816c00611b87b7e2103f202ef0b81a4db738688514ca956515a41020",
          "sha1": "a06d5c51d036530835739f096196b9c8b7a2b39b",
          "md5": "81b5e848f58587ba9d4f188bda2e39a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3-sources.jar",
          "url": "livekit-android-2.20.3-sources.jar",
          "size": 921092,
          "sha512": "ae3ea6263225956224493ef88a5c67adae6aa40751276513b348bd68ecad0bf74c120964f0497a314b3d25bb5ad445f069d22a5c33d3939990f8ef79278cfc38",
          "sha256": "73877380557bb09c9c4d5b5829f2b8c1a63f8fd3c62902c56bb8de9d7f4ef1c4",
          "sha1": "2e7c2ac2d503706316776b25ef8b628cebf1e2dd",
          "md5": "56d53fd2d0775359b077617f8e93a3c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3-javadoc.jar",
          "url": "livekit-android-2.20.3-javadoc.jar",
          "size": 6836480,
          "sha512": "bae13ebbde0c6c8c15823ce6203fd8a116b25e6f1b81bdc9ccc11adc681aa6ebcb57d402a9e2fbc64182160ef076eb830389f2d175b3e37f33fd1d0933cc0c99",
          "sha256": "b0a78b403a9af39b4db1bb913b6671bd5978c721e32295b76be09b48173c8ce5",
          "sha1": "ac0747dc33515f6e86aa0a047928b1a8a46c045f",
          "md5": "2f1de263835f783778c13d1076f3805e"
        }
      ]
    }
  ]
}
