{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.06.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.12.2.aar",
          "url": "livekit-android-2.12.2.aar",
          "size": 2786691,
          "sha512": "dfde7608ce140eca2ced57b636cb7faf8ea685430342c7684c16729d8c95a79a4d0584a4e3322758910dc13187cfa18707ace831d22fac1116e25ab53a8e9cac",
          "sha256": "eceb2d14020a499c1a14bf650921c7adf3c3883c58382280e1266eb563e6aaa3",
          "sha1": "3e07b424a32b6adf1547a8bf262d0e2d11455efe",
          "md5": "0854831c19b210c2469db2543a563dd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.06.1"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.12.2.aar",
          "url": "livekit-android-2.12.2.aar",
          "size": 2786691,
          "sha512": "dfde7608ce140eca2ced57b636cb7faf8ea685430342c7684c16729d8c95a79a4d0584a4e3322758910dc13187cfa18707ace831d22fac1116e25ab53a8e9cac",
          "sha256": "eceb2d14020a499c1a14bf650921c7adf3c3883c58382280e1266eb563e6aaa3",
          "sha1": "3e07b424a32b6adf1547a8bf262d0e2d11455efe",
          "md5": "0854831c19b210c2469db2543a563dd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.12.2-sources.jar",
          "url": "livekit-android-2.12.2-sources.jar",
          "size": 735193,
          "sha512": "50ba87fca4debcbd8f6f5f7cc1af64da4512f2a04cfaeed9dc8d6280263b00428d9e4d22e9abffe41b2f38da3de32b48abee17a1064ceede307d39cc83a1a657",
          "sha256": "da8091bef77c928a1eb7e1d73a408cc919b61e199f11f09f1c8edcaf7f0e28db",
          "sha1": "5ed197abdcdfde97086844d1548200fc595370a5",
          "md5": "240e6d2887f1c05edb1a9e4721b1b956"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.12.2-javadoc.jar",
          "url": "livekit-android-2.12.2-javadoc.jar",
          "size": 5503177,
          "sha512": "ebd32e79ffc50e9e91b5f19182b23c392b5232f56f0eae079a7dae2f8876025e5fec089c85cb37cbfc05d4882c09c17edb0946ac6bd9444d7812cbd860aa423f",
          "sha256": "c40a554cd6893a068dddb7176058b7ea1ccbde20654d07416c9a0ba5bd2cd439",
          "sha1": "b338e9196de32f3dfdd5ec3821e1d0b8c0d8c75c",
          "md5": "c862224fa4346312634fa680e280e654"
        }
      ]
    }
  ]
}
