{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.27.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.1.aar",
          "url": "livekit-android-2.27.0.1.aar",
          "size": 2876891,
          "sha512": "6686c838c8a9c16750ae3c4de6a33d184ec75c68d8825e0e89d076fddff17503583bab29f06986db344eab600c23167cdc27a874586ab23c717972e07919e7d8",
          "sha256": "d02160f7220137798d0ba97a21d3552fc4954670f19962c4e52a0588fe146489",
          "sha1": "d091b948bc4f8d028ac7b3ffb712690222122c90",
          "md5": "6aceae5ecae7cb07bd2551cd82adea3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.27.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.1.aar",
          "url": "livekit-android-2.27.0.1.aar",
          "size": 2876891,
          "sha512": "6686c838c8a9c16750ae3c4de6a33d184ec75c68d8825e0e89d076fddff17503583bab29f06986db344eab600c23167cdc27a874586ab23c717972e07919e7d8",
          "sha256": "d02160f7220137798d0ba97a21d3552fc4954670f19962c4e52a0588fe146489",
          "sha1": "d091b948bc4f8d028ac7b3ffb712690222122c90",
          "md5": "6aceae5ecae7cb07bd2551cd82adea3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.1-sources.jar",
          "url": "livekit-android-2.27.0.1-sources.jar",
          "size": 644517,
          "sha512": "67d14ab13a6e4fa252878378b37e5354ff2498f7247de602f3d565fac5e6e45c0438264470ab38c9efa4f4050023494be8336c5c167c4e165d7b01a7b81cd243",
          "sha256": "a313e2b5dc5fb65ee6b2b74cf57fed100f24a2535604efbed8ab74c2d2669be4",
          "sha1": "82f2043c4141af2c80da8a6c85f1d54c548203b1",
          "md5": "4c6f4a7899f9ccc80a167e6517c14e1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.1-javadoc.jar",
          "url": "livekit-android-2.27.0.1-javadoc.jar",
          "size": 4126500,
          "sha512": "b6fe1da1b5f81c506772cb1f4062da65220a808ae1a5fc64e28e496a08dacce5309ae3a3d26118af692f434a33a6a50c693aca6e7cd76f3f25529a7ad30e58b2",
          "sha256": "83103a544bc23a052f1adbd7bb0e5466a542472a74966e13dc8c90d45e99ee1c",
          "sha1": "a7498a48f4c67bc80c52e0d4eb0428529c41a788",
          "md5": "2d9ba076294dd4e389db48f67a035196"
        }
      ]
    }
  ]
}
