{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.13.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.4.aar",
          "url": "livekit-android-2.13.1.4.aar",
          "size": 2939739,
          "sha512": "1afaf38abc322a1d16ddadc8a9020f868ddb415b5e36ad10d543f672a25b21a34dec9ced6f02d3dc9c6b31d2dfe560879e6d88e7c0727c4e3543e0b7b67d5196",
          "sha256": "83ecd4d59ea1e2d97557680b7e3c04d45f663ab9bc6d56d4d2fe3bf378e73f88",
          "sha1": "46f702be29b19da28876a61a5c4dc263a4ecd9c0",
          "md5": "925df09dbc0c246b8ddb6465775d756b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.4.aar",
          "url": "livekit-android-2.13.1.4.aar",
          "size": 2939739,
          "sha512": "1afaf38abc322a1d16ddadc8a9020f868ddb415b5e36ad10d543f672a25b21a34dec9ced6f02d3dc9c6b31d2dfe560879e6d88e7c0727c4e3543e0b7b67d5196",
          "sha256": "83ecd4d59ea1e2d97557680b7e3c04d45f663ab9bc6d56d4d2fe3bf378e73f88",
          "sha1": "46f702be29b19da28876a61a5c4dc263a4ecd9c0",
          "md5": "925df09dbc0c246b8ddb6465775d756b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.4-sources.jar",
          "url": "livekit-android-2.13.1.4-sources.jar",
          "size": 778723,
          "sha512": "d494d5a3d0323963c25c1f9650cb5e1136722124aa0da981f974af18e374d7ac31fc840c14312be61fe88c00de7aaff187b7244e2b94096e89e8f7576203cc78",
          "sha256": "e81365b9cc0b69bf7d191a7581aaa8fb6f492590f2e5ffa378c472840bfff148",
          "sha1": "f8b87514802bd4000539fc24d4746a92dc440ad3",
          "md5": "3a24dc8120a19e42dbb810f163ea25a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.4-javadoc.jar",
          "url": "livekit-android-2.13.1.4-javadoc.jar",
          "size": 5757928,
          "sha512": "77f3e3b8aa4519d7d600cd52b1fbddc373b92a4c2c0d10cde6baac0dc49b4f87ec644019e29c4379ab8f51262fb552461c19d73dbe3d4ec012df132740d767b3",
          "sha256": "c31864bff8512075d58e095b2abc62ebfb338e9a9aff1b37c601d1429df1c26a",
          "sha1": "b75b66a636239d5ef3a8dc8871ab75ea1103c7eb",
          "md5": "177eb289a854951a951f4f0a49022d5a"
        }
      ]
    }
  ]
}
