{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.18.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.3.aar",
          "url": "livekit-android-2.18.3.3.aar",
          "size": 3411276,
          "sha512": "aa55086db0cafda3aa56ab26f70ac1f09e22674e085ed5acf87eb0ac7a9093860168e1f25182a310830be8e62260cb8b95c0497647d1bc46c14d7871113fd3c9",
          "sha256": "74bf2e0d16b1f56aecf79f671a415f142fde76cc053c6953b99febc54c46e9d1",
          "sha1": "a2c41e1da28ea006df0cf4fe10ac2233d02d363f",
          "md5": "e65f2c0792453afa464e111ae9dc59dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.3.aar",
          "url": "livekit-android-2.18.3.3.aar",
          "size": 3411276,
          "sha512": "aa55086db0cafda3aa56ab26f70ac1f09e22674e085ed5acf87eb0ac7a9093860168e1f25182a310830be8e62260cb8b95c0497647d1bc46c14d7871113fd3c9",
          "sha256": "74bf2e0d16b1f56aecf79f671a415f142fde76cc053c6953b99febc54c46e9d1",
          "sha1": "a2c41e1da28ea006df0cf4fe10ac2233d02d363f",
          "md5": "e65f2c0792453afa464e111ae9dc59dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3.3-sources.jar",
          "url": "livekit-android-2.18.3.3-sources.jar",
          "size": 872579,
          "sha512": "33e13391342fe8d38c100c5bb4f807ac371ef86e42896b89edc47cbbedb2c4f5fc158358cc61e647d48d1112044eef8ab00f58d45aa3e831aa1148a429fe3663",
          "sha256": "0935353db597b8fcd53cc67a6be4dae37166d7ce9a7a74d4940f8befb352e83a",
          "sha1": "6b1bb788a312d68da46473b2edbeb88ff2dcc49b",
          "md5": "a3864802e35cb29747d556322749a591"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3.3-javadoc.jar",
          "url": "livekit-android-2.18.3.3-javadoc.jar",
          "size": 6523271,
          "sha512": "ad53131bfca62228369361b0776bd753122bf43fc2ba4de025f8025854caa794e5106f09544e716bb0b804847fd009053a69e912df268727100a5a07734c642e",
          "sha256": "c4085e7df02d3de4c371190902ab1e0301d53510abe2c3f58ce5cec91cd0ccb3",
          "sha1": "55041ae43aa3f06ca64dc2ea97b63c3f8c872244",
          "md5": "74985c0e71e580b36f8ef8c0b9534cb7"
        }
      ]
    }
  ]
}
