{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.2.2.aar",
          "url": "livekit-android-2.20.2.2.aar",
          "size": 3568512,
          "sha512": "54f146d87573bd92315d3473315c237edc66bbea18eaad7b02e44cf70d316331c315e786a12757ffe80628221771e159af26bb97ae992735a983480216908aef",
          "sha256": "3ac2a0725617db91a2ed8d361aec7370b3c3d30125fdf3c1c46c3ed57a414b34",
          "sha1": "c54bd80a76c0e1b07f61633c0d2f48066e0ff830",
          "md5": "7a9bf57e452d43748b6d211ee22b8419"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.2.2.aar",
          "url": "livekit-android-2.20.2.2.aar",
          "size": 3568512,
          "sha512": "54f146d87573bd92315d3473315c237edc66bbea18eaad7b02e44cf70d316331c315e786a12757ffe80628221771e159af26bb97ae992735a983480216908aef",
          "sha256": "3ac2a0725617db91a2ed8d361aec7370b3c3d30125fdf3c1c46c3ed57a414b34",
          "sha1": "c54bd80a76c0e1b07f61633c0d2f48066e0ff830",
          "md5": "7a9bf57e452d43748b6d211ee22b8419"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.2.2-sources.jar",
          "url": "livekit-android-2.20.2.2-sources.jar",
          "size": 910400,
          "sha512": "dbf474d771f05bebb2326921d14fb7db7df28850cb8bd9b13015b3acd0158b188f81746e4727b5beb664dd4d6aba34e34dd120fa1e38b234935e2b7602855c5b",
          "sha256": "1e3d5eccce0661f8bbd80b7926e02f39be7d0f8769241cd111d31f5c4581d1c9",
          "sha1": "a08d131466247c2388762f4efd9a8dedaa71881e",
          "md5": "c75206f1048b28abc92db3090d62450b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.2.2-javadoc.jar",
          "url": "livekit-android-2.20.2.2-javadoc.jar",
          "size": 6799263,
          "sha512": "54865cb0504ad2c250e2db52f4a8d1bbc72c82e51b714e0e3c9d8725ee71716cc2e54d711a3644d018037347dcd2bb6fb7f1d6c7cf2519a25c076a055fbad23c",
          "sha256": "0473ecf5c10aa540eef2395d7e31d92643b513553f41af674e25681188fdbef8",
          "sha1": "74820e6fbef2e50a362cff2dab2405cff58b1c9e",
          "md5": "5c68231577220bc2fc3f1a9068c969de"
        }
      ]
    }
  ]
}
