{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.24.1.7"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.24.1.7.aar",
          "url": "livekit-android-camerax-2.24.1.7.aar",
          "size": 46224,
          "sha512": "d2f84cc7c1a3cd05de7a65fcc5b64b2dc5c1a3dd61fe8d0a065e1e14c0ff2b6a58813579760c973c23dc64650529526d347fe5717e89b21406097db458bf14d2",
          "sha256": "2e41944d0e610b2b6f692afc560a569daa07ec2a89da9d506084bc60d1c02597",
          "sha1": "c79f9e6b9d0e424c89f6b61a10801c896f8dd2e3",
          "md5": "8f973f9ed0862da401b4f9b5c8534862"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.24.1.7"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.24.1.7.aar",
          "url": "livekit-android-camerax-2.24.1.7.aar",
          "size": 46224,
          "sha512": "d2f84cc7c1a3cd05de7a65fcc5b64b2dc5c1a3dd61fe8d0a065e1e14c0ff2b6a58813579760c973c23dc64650529526d347fe5717e89b21406097db458bf14d2",
          "sha256": "2e41944d0e610b2b6f692afc560a569daa07ec2a89da9d506084bc60d1c02597",
          "sha1": "c79f9e6b9d0e424c89f6b61a10801c896f8dd2e3",
          "md5": "8f973f9ed0862da401b4f9b5c8534862"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.24.1.7-sources.jar",
          "url": "livekit-android-camerax-2.24.1.7-sources.jar",
          "size": 12887,
          "sha512": "416d63e473c30a7e831f7a51ea4a4a054ec631ac51dea25f59a689c74aa018d0feacaa4b706fa24c2f4e5f94fc8cfbda86cd8016db21240f993afcf548a129c2",
          "sha256": "60dfade43c747c759624abde07f6b4130df43b84ddd21cbf3777c2aceddd603a",
          "sha1": "3ab38567d3373eae87142714ca670c8e0d5dc929",
          "md5": "0cef0041e33e13e341c98ccebfe47566"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.24.1.7-javadoc.jar",
          "url": "livekit-android-camerax-2.24.1.7-javadoc.jar",
          "size": 289968,
          "sha512": "33cf96f87cad7c8c6d3cd6824ed97b96cc997c590f2120444b81593a7ee0a66bdc6db3077183db35f03772b2737e4f3e8b485c6bba12c7ff3b7bb5d1b19bd78f",
          "sha256": "0c7c5d4e217c0cb58d862ad9de297fbc309408317c581c3dbaa1c2af9d9634bf",
          "sha1": "136ca84d441235a148a10daa9c8f83e7151e9098",
          "md5": "75062331848732745d8cbc79e5679647"
        }
      ]
    }
  ]
}
