{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.6.aar",
          "url": "livekit-android-2.20.3.6.aar",
          "size": 3911830,
          "sha512": "828910982a9a2c814f9c03fae4f92c386d591a12445d882424871b6acf484349a92dad9ff47747fabf3d3ae4fa32987670e0d1b0a21437b6c1f5f2b8ad5de951",
          "sha256": "d0e225c593f09afd121c52f022b028a5838b7ab2296fadd53a393e25b15c3692",
          "sha1": "90c3106799638119d0da60cb882884075930cedb",
          "md5": "dff47fdec056848b570121b700146d16"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.6.aar",
          "url": "livekit-android-2.20.3.6.aar",
          "size": 3911830,
          "sha512": "828910982a9a2c814f9c03fae4f92c386d591a12445d882424871b6acf484349a92dad9ff47747fabf3d3ae4fa32987670e0d1b0a21437b6c1f5f2b8ad5de951",
          "sha256": "d0e225c593f09afd121c52f022b028a5838b7ab2296fadd53a393e25b15c3692",
          "sha1": "90c3106799638119d0da60cb882884075930cedb",
          "md5": "dff47fdec056848b570121b700146d16"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.6-sources.jar",
          "url": "livekit-android-2.20.3.6-sources.jar",
          "size": 993785,
          "sha512": "16dc86a25600fad7d4253540d2573a2af41cb1e67c4e2db8e94fc0bbc9e6a690db58d682e32da232ff0b65527fc72f19273566054e2f49df1bd2ed05a5cc90d1",
          "sha256": "582d1894059703914686c8b4894f400583ca9bcb41b61af133696b567bacba81",
          "sha1": "718948ac56001bb6e2148336a8d8c5069db699d7",
          "md5": "6a94f76839deb11aa11afe7a27b72e9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.6-javadoc.jar",
          "url": "livekit-android-2.20.3.6-javadoc.jar",
          "size": 7417124,
          "sha512": "3034d2d516410d4ddab92e25aa5279598f08bd84d9a549f18c64c274a72ca5a7d8a0db78f1bd33c6b5775930c33710ad52f5999fd45ccadd39c93f200283696e",
          "sha256": "27b161baa237f3a2339065ff8fe72f8306dd28f908bad9a00394d1bdeb4b32af",
          "sha1": "fb1254ecd2309690b3bccfd150a1e076d42073bc",
          "md5": "6231b885530fd09566a00e125efb7271"
        }
      ]
    }
  ]
}
