{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.22.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.3.aar",
          "url": "livekit-android-2.22.0.3.aar",
          "size": 3939857,
          "sha512": "050a64de400351d1358756cbe4952ab56543026513019ab6058fa964eff124cca592ec3e22d3e5ce8ab5932e6b4f4108a57e21ee1187157062a927351c21fd12",
          "sha256": "8992fa3249f52c9dba2bfa7240ad12c45adf355a0a382e4774d1da4d7f325670",
          "sha1": "c38976589c311d1b51e5645176dc450193808a0e",
          "md5": "022d0651520807cd84ab6bbb02989b93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.3.aar",
          "url": "livekit-android-2.22.0.3.aar",
          "size": 3939857,
          "sha512": "050a64de400351d1358756cbe4952ab56543026513019ab6058fa964eff124cca592ec3e22d3e5ce8ab5932e6b4f4108a57e21ee1187157062a927351c21fd12",
          "sha256": "8992fa3249f52c9dba2bfa7240ad12c45adf355a0a382e4774d1da4d7f325670",
          "sha1": "c38976589c311d1b51e5645176dc450193808a0e",
          "md5": "022d0651520807cd84ab6bbb02989b93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0.3-sources.jar",
          "url": "livekit-android-2.22.0.3-sources.jar",
          "size": 1000267,
          "sha512": "a427231846b3d6feab21d95dde3af8331b125230e1290db20a6c640d82e5185b23c68171f55beee5174755c4d5cb7e553b4000d7cab03924760ad9631b9b95d6",
          "sha256": "3d3f5e3a96cba86d8fbdede839037f54711f215ee939ffab94e356d0f51566cc",
          "sha1": "0f83d80f29d55733c51284a60a5ffc3edad5b663",
          "md5": "823f678a814976e6bc1c7f49ae1fc4ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0.3-javadoc.jar",
          "url": "livekit-android-2.22.0.3-javadoc.jar",
          "size": 7447831,
          "sha512": "1c51c798718cc6cc3031a084f05bb73aa98f2c08331c5460cee8e1621c62d8f037648844b351d30a5ee9bb103f369a36a937fe08767f192ef44100b515bb6d9d",
          "sha256": "070593800fd42dd63116018b9a113d6719c7a0609a6d178b0c72a95d807f8152",
          "sha1": "d905789f4ae728ac32700636b1fcb01240aaa59c",
          "md5": "cfb5bfd4ad02a5d6d6f44090267af1a2"
        }
      ]
    }
  ]
}
