{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.24.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.14.aar",
          "url": "livekit-android-2.24.1.14.aar",
          "size": 4147074,
          "sha512": "cc78f3f0546281d6cb3e56d3519b0259cc101d526c188917631da5160e098b3416b5d7f29d026d892e094b19ec8da2241ec53f969e75e602b0114eb94ff9bc40",
          "sha256": "9e4f7043e799de9c05d7018adc3dc6e0822d32d070e1d620604841ad0f9361c8",
          "sha1": "22d61644574c2f0b1bbc3d882e934a8b9bc8a6b8",
          "md5": "c7b8cacc9fe6a1964316536409254f25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.24.1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.14.aar",
          "url": "livekit-android-2.24.1.14.aar",
          "size": 4147074,
          "sha512": "cc78f3f0546281d6cb3e56d3519b0259cc101d526c188917631da5160e098b3416b5d7f29d026d892e094b19ec8da2241ec53f969e75e602b0114eb94ff9bc40",
          "sha256": "9e4f7043e799de9c05d7018adc3dc6e0822d32d070e1d620604841ad0f9361c8",
          "sha1": "22d61644574c2f0b1bbc3d882e934a8b9bc8a6b8",
          "md5": "c7b8cacc9fe6a1964316536409254f25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.14-sources.jar",
          "url": "livekit-android-2.24.1.14-sources.jar",
          "size": 1037774,
          "sha512": "24cc86d98da7eda356f67bfb69a765139813815b49054340b7a8a159eb8728bd0562679b6a6ede047b6243547e8ae0bc99c24bf818d6e03a5f0198523fffd776",
          "sha256": "2a6a4d02357e681b461b3421f2d7205f0c8fc32fb6e9442f2591d39543b2d5a2",
          "sha1": "aec408f8fdd199e587956d19f9502a623cd86e82",
          "md5": "cbfb16495403c7d6d7e3d6ca66ba65c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.14-javadoc.jar",
          "url": "livekit-android-2.24.1.14-javadoc.jar",
          "size": 7509989,
          "sha512": "815526317f031f11b8e56c56e59140112c72578f1d301312bbaa5919fe6e72855f3e60b469dbb48d96f1313ea1b98355587d658fa77e299e37ca9cd7e343430f",
          "sha256": "3f6b0ddfe4959bf42f9035ebbd748a2836d72e34ecbcfe2d719e6934694777b2",
          "sha1": "0ab0cb454eaa41f872b58fbbe5a8b75fd4e5a43e",
          "md5": "acb4bc3a6b5cd21f666c82656f1b55c2"
        }
      ]
    }
  ]
}
