{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.3.aar",
          "url": "livekit-android-2.20.3.3.aar",
          "size": 3617373,
          "sha512": "026329d55dccf5a040fbd19a26dd47a33dafc545a5dc1698ee11f1ee09c4b73ac3606f03697ca38e8f984952fd51af05bbc7ffa4ef2a5a64a97d9a7399026c55",
          "sha256": "70ac5d4b8f0f37f517a1fbae62453abd148180a6660a8492ca3f5632603a1f1a",
          "sha1": "b894fc633e66eba46b81511b9f3416bd5f9969dd",
          "md5": "81b6038ed2faa57b2d7f9d652eb30ac8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.11"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.3.aar",
          "url": "livekit-android-2.20.3.3.aar",
          "size": 3617373,
          "sha512": "026329d55dccf5a040fbd19a26dd47a33dafc545a5dc1698ee11f1ee09c4b73ac3606f03697ca38e8f984952fd51af05bbc7ffa4ef2a5a64a97d9a7399026c55",
          "sha256": "70ac5d4b8f0f37f517a1fbae62453abd148180a6660a8492ca3f5632603a1f1a",
          "sha1": "b894fc633e66eba46b81511b9f3416bd5f9969dd",
          "md5": "81b6038ed2faa57b2d7f9d652eb30ac8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.3-sources.jar",
          "url": "livekit-android-2.20.3.3-sources.jar",
          "size": 921746,
          "sha512": "357a196717bd269041fc242af424f1782afed9093a38581e2df1e3e889e243def376a5b68cd7bdc115a5def4538ef0d18ce3dea73fa4143470dfbe5f4bc75e92",
          "sha256": "e45171b2319ad8501003241be3db551ff139a53a9d54fa6fa8cc87bee670b1a0",
          "sha1": "2660b525e688c9961b8be24f962f0ada4a4804bb",
          "md5": "1846d20ffa74843700d17c7dbb083dca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.3-javadoc.jar",
          "url": "livekit-android-2.20.3.3-javadoc.jar",
          "size": 6838765,
          "sha512": "b83f2eb30989202974eeacb4a4e550ffb5213aea8f97ec71b674ff25ead1b4372e16116a893d80f284fd23775d6a252c3f69ce29aa6963eee5e2d3a7f9ca386e",
          "sha256": "699664a56ee231e89e46dc22f9e0a98a785da676ced5ac96600778e53cd1ab85",
          "sha1": "ed07fdfa98b56f5c1ab2c6dd2b5ac794d3190904",
          "md5": "5671de59726edb14dd310fc1fda9b8e5"
        }
      ]
    }
  ]
}
