{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.13.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.6.aar",
          "url": "livekit-android-2.13.1.6.aar",
          "size": 2939408,
          "sha512": "d85c4238db10bf01d728fd3c5453d70e6c815e07fa5e388704cd2a7652a6e27fb0fe1eb2bd696b79ed64dc112acc980f56b6a5fe24f39f35d22a03ee9020ef59",
          "sha256": "117cce4192a1e552fa76ca49767c52355cc046e715e403ae1efcf688f2e69428",
          "sha1": "41e0da3a14ba1849ccd909d608146992a256e80f",
          "md5": "859d312ea5e251e52f491f351225d2d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.6.aar",
          "url": "livekit-android-2.13.1.6.aar",
          "size": 2939408,
          "sha512": "d85c4238db10bf01d728fd3c5453d70e6c815e07fa5e388704cd2a7652a6e27fb0fe1eb2bd696b79ed64dc112acc980f56b6a5fe24f39f35d22a03ee9020ef59",
          "sha256": "117cce4192a1e552fa76ca49767c52355cc046e715e403ae1efcf688f2e69428",
          "sha1": "41e0da3a14ba1849ccd909d608146992a256e80f",
          "md5": "859d312ea5e251e52f491f351225d2d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.6-sources.jar",
          "url": "livekit-android-2.13.1.6-sources.jar",
          "size": 778828,
          "sha512": "904b54d18911dee7ef39d026df26becf90d0cd1bdc8de3aab353cffddf609a9d649eb159c50a457df87bd3e031a866d1185be47dedf69b3eab8b94931a215583",
          "sha256": "909677ae85371c21548d398230bcea66cff44f79c589f74877d727be99c8686c",
          "sha1": "ff2947cb7da10c90f4242f5c2c768c87cfac0d21",
          "md5": "e56ab37220f58f3820d135265f4d3a77"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.6-javadoc.jar",
          "url": "livekit-android-2.13.1.6-javadoc.jar",
          "size": 5758124,
          "sha512": "b734722691404ab529a0baeb748519c8f030dc2afc2145a5f41c5885a471cdc272aaa31979e81d185333eba1f364643459d1e14bd4155146c7b0a83fc89e9e27",
          "sha256": "e1fbfb4d39770ffde924d96a15c5ff6249472458a82798376de7f4f13f343156",
          "sha1": "2a5e203227357d876e329026dbf095cd2e7c0549",
          "md5": "2b3a21ac780d3e794410add966b7da87"
        }
      ]
    }
  ]
}
