{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.6.aar",
          "url": "livekit-android-2.23.5.6.aar",
          "size": 4057339,
          "sha512": "53ca29aee0d271e419909bf8498e88e2216a9388e63110172685a49b4d024ede8f2afe06215a96af1a5718022cf35d82cc9b1813b061d16e5a83fbcc0cb49b0d",
          "sha256": "7112cd9deb01087169aed420e3957093708ba885a99e693668db2345116eb420",
          "sha1": "e632641bace85a32e018d4e28a7d4396bb932322",
          "md5": "e5acd58dcd0dbc3a1a1ba4475b5b659e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.23.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.6.aar",
          "url": "livekit-android-2.23.5.6.aar",
          "size": 4057339,
          "sha512": "53ca29aee0d271e419909bf8498e88e2216a9388e63110172685a49b4d024ede8f2afe06215a96af1a5718022cf35d82cc9b1813b061d16e5a83fbcc0cb49b0d",
          "sha256": "7112cd9deb01087169aed420e3957093708ba885a99e693668db2345116eb420",
          "sha1": "e632641bace85a32e018d4e28a7d4396bb932322",
          "md5": "e5acd58dcd0dbc3a1a1ba4475b5b659e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.6-sources.jar",
          "url": "livekit-android-2.23.5.6-sources.jar",
          "size": 1017159,
          "sha512": "704030772fdd13e0c1d207d96138fd3f323cce1a58c81a69b1fc421b79c8d8b48c1850729a7e61585f9f3272aa83476f500d50adce04e7295ab9e6641a5d3725",
          "sha256": "9be1ffc22c17a03116c0c614419080737fad81f7f6ff4b2954c4be9ed8fc2938",
          "sha1": "c489d9f5cbbd3e29cf0529887d746c310267987e",
          "md5": "60379c22e0e84e30788d190e353458d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.6-javadoc.jar",
          "url": "livekit-android-2.23.5.6-javadoc.jar",
          "size": 7475017,
          "sha512": "9a1220447b94c1123b430bb4b18e87863a2274decd5a0c1bfe61604ab952bd9599d22b602b414d8cbeac5c8a6a483c83ae15755d4716563d506f199bf98a4d68",
          "sha256": "a70760de7adad43cf65d9d287a67ecf11e4046383f1625eacd01588a8ebe80bc",
          "sha1": "f6547ca8c6d89fd095910965b556486916ea9c62",
          "md5": "ea9a41de572df4dd8ff61032b36bbeae"
        }
      ]
    }
  ]
}
