{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.23.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.2.5"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.23.2.5.aar",
          "url": "livekit-android-camerax-2.23.2.5.aar",
          "size": 46216,
          "sha512": "2c715e7130a81451f6bddf6f489a43b88e9f809432896eca6896f716cf8d0dcc6b4cc5d616dc68adcc2d90a2c417f7d6b68fcb5b1255003c6c4314574dd6066a",
          "sha256": "7127aad3d3dc97061fce930c89d3ad41778f323b7ac8dc030db7eac59354404f",
          "sha1": "313ded49ab354d99e321715f1a3ee65a2454a217",
          "md5": "0f5e8c84fbf29ff32fe614cb7a3e65a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.2.5"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.23.2.5.aar",
          "url": "livekit-android-camerax-2.23.2.5.aar",
          "size": 46216,
          "sha512": "2c715e7130a81451f6bddf6f489a43b88e9f809432896eca6896f716cf8d0dcc6b4cc5d616dc68adcc2d90a2c417f7d6b68fcb5b1255003c6c4314574dd6066a",
          "sha256": "7127aad3d3dc97061fce930c89d3ad41778f323b7ac8dc030db7eac59354404f",
          "sha1": "313ded49ab354d99e321715f1a3ee65a2454a217",
          "md5": "0f5e8c84fbf29ff32fe614cb7a3e65a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.23.2.5-sources.jar",
          "url": "livekit-android-camerax-2.23.2.5-sources.jar",
          "size": 12882,
          "sha512": "533b7ea91ec8920aaf80b8319046daf41062ceac1c9b5d8333bafafa4c2162223805cc27a8a2fe1cd8356772e4c4e1d0871ccb0ffe3de7050eeadeca4a758aaf",
          "sha256": "90732703e5ec49de6e83ff5f5034668208a6830a27c94c3df25388aabec987ba",
          "sha1": "700995c17938353c974ae3d2930d5b9fd60b9cd1",
          "md5": "6793cb49c29a5f9dd7d2231bae54425c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.23.2.5-javadoc.jar",
          "url": "livekit-android-camerax-2.23.2.5-javadoc.jar",
          "size": 289969,
          "sha512": "ff137fa58114b99951add106490a7dfb86fcf4d0459c59c4da5050d3761c38d522356bf5157d0cff8d989295e2a5d22e34d249047d9240c64f40bf169a3f2b9f",
          "sha256": "e5624f8ea76f1b111cfd428ded0b8187f0b4eaffa4f93ad0b6563d36c8eb6a70",
          "sha1": "6c5ac2c5eeff99bd322063cfd00b9f618398781e",
          "md5": "2018f9d504d79b515eb7bcda342827c1"
        }
      ]
    }
  ]
}
