{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.19.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.19.1.2.aar",
          "url": "livekit-android-2.19.1.2.aar",
          "size": 3479400,
          "sha512": "0a43dc8ed51c2672aea0935275a92d215e6ec556db9c21e7cf4b2ed25739af6e6418c800ceeacc1f0672736c85f1be522cfd99a273c473706ce14660ce92bff0",
          "sha256": "0993f61662af83dcf98b77905ba33733d926c6860db96d46e75b6bb6996632d3",
          "sha1": "965eb26c2d3d114941398e5eb6a581a38959d684",
          "md5": "c268ec021c989c6b3aaa746ce1aabc28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.01"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.19.1.2.aar",
          "url": "livekit-android-2.19.1.2.aar",
          "size": 3479400,
          "sha512": "0a43dc8ed51c2672aea0935275a92d215e6ec556db9c21e7cf4b2ed25739af6e6418c800ceeacc1f0672736c85f1be522cfd99a273c473706ce14660ce92bff0",
          "sha256": "0993f61662af83dcf98b77905ba33733d926c6860db96d46e75b6bb6996632d3",
          "sha1": "965eb26c2d3d114941398e5eb6a581a38959d684",
          "md5": "c268ec021c989c6b3aaa746ce1aabc28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.19.1.2-sources.jar",
          "url": "livekit-android-2.19.1.2-sources.jar",
          "size": 889228,
          "sha512": "1bb9ce19928ad1f70564502b859bfff11a4bf04a6ccb98e01aa24cd536f8f2c3d4ea1ce0203448b65e0068855769d24174befb3f558902e1a7fa26943ac41b74",
          "sha256": "a27bba343b1f6e5cfa27f4b146f226fedcbe24f9a104e875bc183bb02dd5fe37",
          "sha1": "782d6efbe5e3975b261540b69f320227153d7e36",
          "md5": "157cc5c82b364519b642636a4c70d45d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.19.1.2-javadoc.jar",
          "url": "livekit-android-2.19.1.2-javadoc.jar",
          "size": 6608796,
          "sha512": "5eb43cafe52d49da4f8a55c8771635f8e21251f705d513039e0ce16baae272811a6a413f0b9613da15d06d31323bef83e6299646a4d6a476366a5ce753a0ac7d",
          "sha256": "2c9d7a1391da3cc677458ccd4d2f946f68e90400865e4ea8019b794e221b1296",
          "sha1": "9ea07dee6d9ddcdd67ca3546f7dd0f19cb7d5360",
          "md5": "8f516c87255f14fe369c6350b782cbc2"
        }
      ]
    }
  ]
}
