{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.5.aar",
          "url": "livekit-android-2.20.3.5.aar",
          "size": 3910653,
          "sha512": "dbbe4b277293ed92bca773b75f9daf7c86341d3d88dd3640024909a4841424c1030aa0ed511f070c7ac14326213b483b711c4f0ee68874885eb7e3719ab4b0af",
          "sha256": "17dab388ea930f25bde526748f1406471b1e3a4df419fd766feca24abe629cd2",
          "sha1": "abb6286f9b3985ec453c0f1c03ffe040dbd18a94",
          "md5": "471060ac3a50482dd46c7ef5ced56959"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.5.aar",
          "url": "livekit-android-2.20.3.5.aar",
          "size": 3910653,
          "sha512": "dbbe4b277293ed92bca773b75f9daf7c86341d3d88dd3640024909a4841424c1030aa0ed511f070c7ac14326213b483b711c4f0ee68874885eb7e3719ab4b0af",
          "sha256": "17dab388ea930f25bde526748f1406471b1e3a4df419fd766feca24abe629cd2",
          "sha1": "abb6286f9b3985ec453c0f1c03ffe040dbd18a94",
          "md5": "471060ac3a50482dd46c7ef5ced56959"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.5-sources.jar",
          "url": "livekit-android-2.20.3.5-sources.jar",
          "size": 993504,
          "sha512": "232696d44fd15735f5e84969f871ba60fcff37d0f9899096cdcaa54ec2278317d5b82bd5c84eb0140a963184cbf35fc32d047d50a6511eb5efff28254c3cdc3c",
          "sha256": "27346cf267c0da536e949aa9a543c41b09db2f6c538d3bb49c159b3b935e41a6",
          "sha1": "812665d8e4f86682319af7d98730cc20bcbd044f",
          "md5": "421463adb0ebf320480ec5562d81e8b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.5-javadoc.jar",
          "url": "livekit-android-2.20.3.5-javadoc.jar",
          "size": 7416919,
          "sha512": "417a78415a78255de0daa96fc9a065e50c9ba0d9e29a1081aa6b5e5097080cffc9f76195f33896fd8d24c84b4407fefa8079acd4600d0ab5d02244fa9d5470b1",
          "sha256": "7663ee0c7ffac0f6dabcfc9b32d1317899996de085a2ce54c0e3fb2b7b58886e",
          "sha1": "7f591e66b236ce5dca258b4f7fd1447cfd853baf",
          "md5": "8ae0b77584bcc2f1fbe2b380713a9701"
        }
      ]
    }
  ]
}
