{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.2.4.aar",
          "url": "livekit-android-2.20.2.4.aar",
          "size": 3560391,
          "sha512": "e076c45cf3bd7dd5c636d6cd9efde4e95e0d0c5528f9410ed148e28e5622c1d4c5ae65e1756492e854afe72b93bc1453e08d1bbbae52fe3b88339fc191355e2e",
          "sha256": "671c297603bd6467c1e185fa5be428794527bf01162196eb8eeab8290c75c956",
          "sha1": "a6d7589b9e4ba12726a4814f1c3b4215fc8aabe9",
          "md5": "d6455cc99ce5063dd167807db1dbef85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.2.4.aar",
          "url": "livekit-android-2.20.2.4.aar",
          "size": 3560391,
          "sha512": "e076c45cf3bd7dd5c636d6cd9efde4e95e0d0c5528f9410ed148e28e5622c1d4c5ae65e1756492e854afe72b93bc1453e08d1bbbae52fe3b88339fc191355e2e",
          "sha256": "671c297603bd6467c1e185fa5be428794527bf01162196eb8eeab8290c75c956",
          "sha1": "a6d7589b9e4ba12726a4814f1c3b4215fc8aabe9",
          "md5": "d6455cc99ce5063dd167807db1dbef85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.2.4-sources.jar",
          "url": "livekit-android-2.20.2.4-sources.jar",
          "size": 910334,
          "sha512": "03c79856dca9e6d63656d2b4cf397d2c0a814ba2c8f57fc6bbaaddf3010569baa12b40cd2c06511f96f8b8f8cfe5d9663703eaff0ddaacbf566e5804b09b86d3",
          "sha256": "bc288382f327a227472e70c1c25a31c53ac7c76fca6ed906f93bf4a21a29e84d",
          "sha1": "604894412f47766a2e3080827809da4ba49da8a0",
          "md5": "132fe8082251cb6f6748b7e614a5873d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.2.4-javadoc.jar",
          "url": "livekit-android-2.20.2.4-javadoc.jar",
          "size": 6769566,
          "sha512": "9b556c4b55f701deb6346bd8936c0c9978401645545f0df081138a9b1ad3a1786a184f16bdce028ead538db527985373eeb4f7340c44256d70f3bfed5bc65314",
          "sha256": "3f29b4974a010eed19ed715526bcc27b379b4e9aa2f6ed20f45834ec08d94f45",
          "sha1": "3c6090572fe06e2310c28276c63d39d808327e5d",
          "md5": "94690792b4b17d862beda2e91351bb20"
        }
      ]
    }
  ]
}
