{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.2.aar",
          "url": "livekit-android-2.23.2.2.aar",
          "size": 4028946,
          "sha512": "ccef70d43cddf03a248761d9d2bd71ddff3cad81589b212efd4a47cf2c5d4c5a35c22a12cd57344a03509334e6aa8969d7ebcfaafac94963dbaf367054833a53",
          "sha256": "447043d496be5377b26be8be7a9f5cdbd95509dab939256251a064c56dddbbe3",
          "sha1": "5e41a8b3007f25e6670116b709cefe4a64fd3bec",
          "md5": "9fca8cc0b8ea87e7707d0286386b5180"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.2.aar",
          "url": "livekit-android-2.23.2.2.aar",
          "size": 4028946,
          "sha512": "ccef70d43cddf03a248761d9d2bd71ddff3cad81589b212efd4a47cf2c5d4c5a35c22a12cd57344a03509334e6aa8969d7ebcfaafac94963dbaf367054833a53",
          "sha256": "447043d496be5377b26be8be7a9f5cdbd95509dab939256251a064c56dddbbe3",
          "sha1": "5e41a8b3007f25e6670116b709cefe4a64fd3bec",
          "md5": "9fca8cc0b8ea87e7707d0286386b5180"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2.2-sources.jar",
          "url": "livekit-android-2.23.2.2-sources.jar",
          "size": 1007120,
          "sha512": "fb299b4cc31155ffeb7d40e82d9257d019e682df1c6e5ec4bc429999b3304bca93de87ef7190e25490b3b53f577910ce7d0cca05684d54049c76033491ed832d",
          "sha256": "42c9e8df4f77a7a0342364d49b855edf366c98388c960973f996a80804fbe269",
          "sha1": "358a979a430d31bc5b8445b7962a38a077fa1c55",
          "md5": "f5c4bae011288028092f18b027592562"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2.2-javadoc.jar",
          "url": "livekit-android-2.23.2.2-javadoc.jar",
          "size": 7471318,
          "sha512": "b39a542ecf18fff50d07ac7d141f30457c253f8c4bd885d08c430ebe19a948ac31d38b3f35c10d412cf486318b5b5d88168fc2e55543ae746f96fe960eb14361",
          "sha256": "5e506b19a4a7f5bea872d8549069d0262377ba2fe06411aa717e50a3f0a114ad",
          "sha1": "ab6ec38dc3c91f73634c5ee62d80962ede8f4b4e",
          "md5": "dffec0f4f27addb94752e2deb11408e3"
        }
      ]
    }
  ]
}
