{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-track-processors",
    "version": "2.23.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.23.2.5.aar",
          "url": "livekit-android-track-processors-2.23.2.5.aar",
          "size": 41706,
          "sha512": "5f74eb5094a0fa26bb5a11cf9703a0949b30f0872062a1a34e50f8403ad91ecbbe767f3204e5b0e8443f5a3bb7c6558fd90b1293e0a62e7707ef211d003eecbb",
          "sha256": "cb0ff357e78c348a69c6996455a42f34cbcdc6f6b7c27dc3b4fe5eecfb0798b5",
          "sha1": "c8673153433226217f9008017ff617dd7ff4b0b4",
          "md5": "76626bb66a8d6dbe6a2717c9484bb8f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.2.5"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android-camerax",
          "version": {
            "requires": "2.23.2.5"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "segmentation-selfie",
          "version": {
            "requires": "16.0.0-beta6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.23.2.5.aar",
          "url": "livekit-android-track-processors-2.23.2.5.aar",
          "size": 41706,
          "sha512": "5f74eb5094a0fa26bb5a11cf9703a0949b30f0872062a1a34e50f8403ad91ecbbe767f3204e5b0e8443f5a3bb7c6558fd90b1293e0a62e7707ef211d003eecbb",
          "sha256": "cb0ff357e78c348a69c6996455a42f34cbcdc6f6b7c27dc3b4fe5eecfb0798b5",
          "sha1": "c8673153433226217f9008017ff617dd7ff4b0b4",
          "md5": "76626bb66a8d6dbe6a2717c9484bb8f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-track-processors-2.23.2.5-sources.jar",
          "url": "livekit-android-track-processors-2.23.2.5-sources.jar",
          "size": 17073,
          "sha512": "e859418353802bb8d6fcfe5fe94a35453b598904280108a001d3db710e6121f53600ab886ee99eafa5fafb5ca770249cde8e928d3cf8517907e17c2885da1c67",
          "sha256": "bd8308a24003c340f7d4a7b79755c796caa4e25c063650943e8982e53d914ad0",
          "sha1": "21a22e07855480bd3c2af87909fddb73e8b73635",
          "md5": "f7b782dd6aada2d08952a4ae18f4e6a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-track-processors-2.23.2.5-javadoc.jar",
          "url": "livekit-android-track-processors-2.23.2.5-javadoc.jar",
          "size": 294535,
          "sha512": "4a55191681622df0f399853ea28d9797d66a01c7fc3612fe4daa1fdfb7ab0367e33b868afac83a3b73b4c8c6bd6eeaad45d57af5051977a6e2eb6084b8f4e8d2",
          "sha256": "57e103a5ac1740157dee11d1b164b9320f84634c68a7b27b1af3db6511aefc93",
          "sha1": "fb64e207fe66ed2d16e20e4157ed736ab33bbe01",
          "md5": "b54e55cb799d5480084e61641a7d12d3"
        }
      ]
    }
  ]
}
