{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.23.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.23.1.aar",
          "url": "livekit-android-camerax-2.23.1.aar",
          "size": 46095,
          "sha512": "df148884e51c7a9319da79e3057171c5bf9b553f07df67ff3b58dd7745443e9c07c2206bb9c39fbfe5ff234358fb4b92d00d134bfadb0486c82e153871d97830",
          "sha256": "6ce783aac37a2df086a59d27abac765292ebc53fb8935dc4910e198a79d0c5ea",
          "sha1": "86417c57cdb86535c05ef160a1569786c6c110ba",
          "md5": "769e458de07979c44c76509952a02861"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.23.1.aar",
          "url": "livekit-android-camerax-2.23.1.aar",
          "size": 46095,
          "sha512": "df148884e51c7a9319da79e3057171c5bf9b553f07df67ff3b58dd7745443e9c07c2206bb9c39fbfe5ff234358fb4b92d00d134bfadb0486c82e153871d97830",
          "sha256": "6ce783aac37a2df086a59d27abac765292ebc53fb8935dc4910e198a79d0c5ea",
          "sha1": "86417c57cdb86535c05ef160a1569786c6c110ba",
          "md5": "769e458de07979c44c76509952a02861"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.23.1-sources.jar",
          "url": "livekit-android-camerax-2.23.1-sources.jar",
          "size": 24909,
          "sha512": "bd7298bda2c4f14359a001590dcf71514f2e6112e94d688e26fb28ce0514b836c8c31752d87a57eb0e80a4d05f23eb58f25c0a9c583efda418d964b50d67746c",
          "sha256": "4282e7f41f43978b1f13d2e7f8c49f094893f172c2c0d9481ce288d5f8c902d6",
          "sha1": "fc349570a27e14925aeaf61b4e26c25005985e0e",
          "md5": "9aeb2ea4fddd98a94996df980152c52b"
        }
      ]
    }
  ]
}
