{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.13.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.8.aar",
          "url": "livekit-android-2.13.1.8.aar",
          "size": 2940346,
          "sha512": "c1421bcea4efac8674b438b225c6af4f1d7149cb37885d2350b1c4ca53c1d71720fc60e626ffef6f13e3bca03cf4fd227ff82d3ad06623f563e2d9a952cff92d",
          "sha256": "756903bf62a91c779b8cd5c2f135a8b7f310302abda653dcb18507c4a4debfa1",
          "sha1": "637ad2005d1dc5f0a7beebca812be850a9a1441e",
          "md5": "2e621b3841473075ebf9d0897801816c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.8.aar",
          "url": "livekit-android-2.13.1.8.aar",
          "size": 2940346,
          "sha512": "c1421bcea4efac8674b438b225c6af4f1d7149cb37885d2350b1c4ca53c1d71720fc60e626ffef6f13e3bca03cf4fd227ff82d3ad06623f563e2d9a952cff92d",
          "sha256": "756903bf62a91c779b8cd5c2f135a8b7f310302abda653dcb18507c4a4debfa1",
          "sha1": "637ad2005d1dc5f0a7beebca812be850a9a1441e",
          "md5": "2e621b3841473075ebf9d0897801816c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.8-sources.jar",
          "url": "livekit-android-2.13.1.8-sources.jar",
          "size": 778979,
          "sha512": "d48d535f8c25511e6874c292291adc8d53220a361a0279715a383ed934c58a054e024cf62b8937f1925f9e1ba402fb06a1e385690eba7667fd1533232268ee9c",
          "sha256": "51d6406142525a6e5763e0ca25249aedfcaddb9dcf4214d72e648843f0f9e481",
          "sha1": "493e5445aac9429f48242e621a038c07a744b741",
          "md5": "3207b6f1d7f091fb3a3ef8bc856ddb5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.8-javadoc.jar",
          "url": "livekit-android-2.13.1.8-javadoc.jar",
          "size": 5757983,
          "sha512": "03a129a787678107246cad54d3fb6c75b42d6267421c3f7a7da8d490f585af9e3c633db9cef9c52668633616cac2b7db2a862d3bf5edbb0d0943aa6fdc4c30c4",
          "sha256": "4b991d1501dbc27768125c8055315a6bb5ed88f7db9bf5b6315bc0bb9ad244e0",
          "sha1": "6dc1ebf6298e655c9678feba6ae1364aafab751c",
          "md5": "beb8d313dd89d7be0a065908d915f65d"
        }
      ]
    }
  ]
}
