{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.aar",
          "url": "livekit-android-2.23.2.aar",
          "size": 4018771,
          "sha512": "2b97e22b9493b460b7f303ebfcf4ab2d85254dd088051c4301cf2656c947554cf9fe8bf356f29d334927376038962b5b5309cc97ae4dcc6cccadc523d45afcc6",
          "sha256": "26b3ed51aab1b34b76a322654f0a132f11a1019f5e7c67b847544f6c8571fa63",
          "sha1": "80c4fe6752d772f31cc7dd8666c09463d9caa64d",
          "md5": "0f183e2bb96bbf2f59335247e4b85a55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.aar",
          "url": "livekit-android-2.23.2.aar",
          "size": 4018771,
          "sha512": "2b97e22b9493b460b7f303ebfcf4ab2d85254dd088051c4301cf2656c947554cf9fe8bf356f29d334927376038962b5b5309cc97ae4dcc6cccadc523d45afcc6",
          "sha256": "26b3ed51aab1b34b76a322654f0a132f11a1019f5e7c67b847544f6c8571fa63",
          "sha1": "80c4fe6752d772f31cc7dd8666c09463d9caa64d",
          "md5": "0f183e2bb96bbf2f59335247e4b85a55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2-sources.jar",
          "url": "livekit-android-2.23.2-sources.jar",
          "size": 1005207,
          "sha512": "dcb15ee8b523f7b22e8eb468f449010fca726d19c0e9c34de02425e18bfd4baaac62d794ec009687dad3ea1ccc7639f1c6e266c6daa283da8a055b15677faa20",
          "sha256": "6a2544ea7c29d5918b73526e0d7bc5bbd4d8b3babffd33c176a375f33b53aa0f",
          "sha1": "dce76e26386a458fa1a08770a7e9bc8727a998b6",
          "md5": "d6e2485f9aad74ec1d07b95d897f1063"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2-javadoc.jar",
          "url": "livekit-android-2.23.2-javadoc.jar",
          "size": 7456041,
          "sha512": "999f66ec363f225ffdcc4d7ebebc4da68582649a49b1eee9a1ccb99b8447c73cc676825e2b31bda63d22f9b754152384bb701f476e32d33a9be652d8700e98fc",
          "sha256": "693d064e0f4dc8bd7d0d3ab13c386fe89cfe69d972a93a2d48eeeb037c46c9df",
          "sha1": "6d4fd1fd2134c82da72514eb83a2391cd05e0fca",
          "md5": "d0463ae85492f35c05a597e63df60118"
        }
      ]
    }
  ]
}
