{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.18.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.aar",
          "url": "livekit-android-2.18.3.aar",
          "size": 3407917,
          "sha512": "5a5b03dc63f0077c26ee416f2b93aea22ebfeda319b0c10481a1b78e1ba9c93f78e1da2e3319f525ec8adfcb83e64d0e22a1e4501f0079b8f1789103a9d7e8d9",
          "sha256": "46b80394a15dfd9f6c0bd46a78a897408e88c216b0cfecc756acacebc711d679",
          "sha1": "471ef7965f062b6f241466512b8a46703949e866",
          "md5": "7de18f908b7cf1e7b5f4ef51b356f8c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.aar",
          "url": "livekit-android-2.18.3.aar",
          "size": 3407917,
          "sha512": "5a5b03dc63f0077c26ee416f2b93aea22ebfeda319b0c10481a1b78e1ba9c93f78e1da2e3319f525ec8adfcb83e64d0e22a1e4501f0079b8f1789103a9d7e8d9",
          "sha256": "46b80394a15dfd9f6c0bd46a78a897408e88c216b0cfecc756acacebc711d679",
          "sha1": "471ef7965f062b6f241466512b8a46703949e866",
          "md5": "7de18f908b7cf1e7b5f4ef51b356f8c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3-sources.jar",
          "url": "livekit-android-2.18.3-sources.jar",
          "size": 872302,
          "sha512": "87f4e5f37d81cd3df6edf7131e7e833471f290b08af74e5ab3aa75a301b16bfa8724f07cd1a23b94e324876eee728b85274f3cbb480c91cb5c46af5f8206af73",
          "sha256": "190d22866d7431cdd6109716b0d7d04fb40ed3bdff598a49703b6424f8c42c42",
          "sha1": "895f330e62ce7ec6b71428db05c71bc21bdc7964",
          "md5": "3a957079059341d77c18fa3030b3226a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3-javadoc.jar",
          "url": "livekit-android-2.18.3-javadoc.jar",
          "size": 6520650,
          "sha512": "ee4f352142657721d0595e528092ff1b49e444b425a83271a0939eb05be611ac2388884ee59699db8e7c0dfa9ac19cba6ed884133aa7d8518dc6059015e86a21",
          "sha256": "84295ecef634ab303d169b792ae46bdbe26b4ddcfb506b90568af372e5a9d586",
          "sha1": "f26b7dab7986044cdcf0445247b989c4f753490a",
          "md5": "e18d292c6319f03db58f7373a005f0c8"
        }
      ]
    }
  ]
}
