{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.24.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.3.aar",
          "url": "livekit-android-2.24.1.3.aar",
          "size": 4124920,
          "sha512": "dd11fcde8a385991fe3cec7f1fc42326b2e565e4f6e463c1b56c468fa7a8f20ec47aec976d927e9046ff165c7a1f1dac85e95b43fcdeb85d626efbfcc8f10756",
          "sha256": "49f1c2fe291c593667bee5fff947729b0e4e4f3adacfe44c4bcadc193303911e",
          "sha1": "114a9eb43b46426b46dfab7e0db9985d5b85a8e8",
          "md5": "5b0ea4a2bfe987c6d1c29ca57afcdae0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.24.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.3.aar",
          "url": "livekit-android-2.24.1.3.aar",
          "size": 4124920,
          "sha512": "dd11fcde8a385991fe3cec7f1fc42326b2e565e4f6e463c1b56c468fa7a8f20ec47aec976d927e9046ff165c7a1f1dac85e95b43fcdeb85d626efbfcc8f10756",
          "sha256": "49f1c2fe291c593667bee5fff947729b0e4e4f3adacfe44c4bcadc193303911e",
          "sha1": "114a9eb43b46426b46dfab7e0db9985d5b85a8e8",
          "md5": "5b0ea4a2bfe987c6d1c29ca57afcdae0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.3-sources.jar",
          "url": "livekit-android-2.24.1.3-sources.jar",
          "size": 1028169,
          "sha512": "ae176c8fdbf43f9b193a220a97ed81f7f7ece0ad8451124557a07311bd3965eb8e8f5e99099c0113e9dcec55390272a47dd7dda7e036500dbb9d7cd8dc1bd746",
          "sha256": "bb5086ba9fc443d2001d3c94c5774023dce2009aab13ca3fa453393cf6099d4b",
          "sha1": "c679d8a64e0329bab58ffba6cb18000f9b16d32a",
          "md5": "d16118b3101f7a8171ad858c815d0512"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.3-javadoc.jar",
          "url": "livekit-android-2.24.1.3-javadoc.jar",
          "size": 7499829,
          "sha512": "e9f525b1b5f9eb11e69eabb1bb7966f4a62c32b18319d12267deec640fb8bc3dc7a1aaf7c4cf4f60094ccbdae4ad87aea056b48d4aef20ad2e0a387d2646c895",
          "sha256": "0bdb06acaf604fb41adfbf4f48778dc213c2c68b035e1ad91930f607be36e6eb",
          "sha1": "337bf59a2755c63ad4a6af7f0aaab31402010ac2",
          "md5": "89b6762abec191f29e0cd522749f4b02"
        }
      ]
    }
  ]
}
