{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "ttsignal",
    "version": "2.23.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ttsignal-2.23.5.5.aar",
          "url": "ttsignal-2.23.5.5.aar",
          "size": 2606156,
          "sha512": "faa80cccc0e89dc3a27d17f5c98a67d92f39c551a48f4cae49f456053a70e8635b3206f63a5187f97e32455c14c17e8b0b5e81963a9fd3cee68c05df6e732248",
          "sha256": "1afb375b3a60db04ee257edc2b936608867609c6db1c1e9a058217540e7e5c21",
          "sha1": "05658dd3ceebd5e049560379050926e2a3909511",
          "md5": "c744724ea13b4b5f3750c39672c94af6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-2.23.5.5.aar",
          "url": "ttsignal-2.23.5.5.aar",
          "size": 2606156,
          "sha512": "faa80cccc0e89dc3a27d17f5c98a67d92f39c551a48f4cae49f456053a70e8635b3206f63a5187f97e32455c14c17e8b0b5e81963a9fd3cee68c05df6e732248",
          "sha256": "1afb375b3a60db04ee257edc2b936608867609c6db1c1e9a058217540e7e5c21",
          "sha1": "05658dd3ceebd5e049560379050926e2a3909511",
          "md5": "c744724ea13b4b5f3750c39672c94af6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-2.23.5.5-sources.jar",
          "url": "ttsignal-2.23.5.5-sources.jar",
          "size": 5967,
          "sha512": "47a9ae3ff9e4b0e12cc376541e226cb317ad1f82dbdf54f3058732e610a5dcf98f992b5b2816ec04267a60c29557a23523977a08bf6259f167df42361132b234",
          "sha256": "2fcbeb5de38b6bd52dbbd7b2ea6b803a735089db3d064f7d834282a314cbd215",
          "sha1": "12801c94305a61238bfb9b2a79c54a547ef64b65",
          "md5": "6754a8d08608abb2f560c43a013a8095"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-2.23.5.5-javadoc.jar",
          "url": "ttsignal-2.23.5.5-javadoc.jar",
          "size": 300852,
          "sha512": "f1345e2a73258f059c75070b45848302b0b996eb10d8975543d7ee3ace78730a983aebbd092a40f7e37076391d2ab91c15c107c0e71f4307f89a49a6278c8e4a",
          "sha256": "cf89c1c0228113650c95b0e4dbddacd61a2286dfe633642749b184c7a0a22fc5",
          "sha1": "334bcd9db83bb8d8776670b3c4469a2d7a84d60a",
          "md5": "0f9ac6eaa0f4aa1a66077eb5ddef5b7b"
        }
      ]
    }
  ]
}
