{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.24.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.9.aar",
          "url": "livekit-android-2.24.1.9.aar",
          "size": 4138784,
          "sha512": "40f8c21447527f73eb077d3ef2fa9e31f1987d9a86be2bfdc6c29eafa2b3bb03fc4cab355a75c42ff59cb800686ed5d9451953290dd7210a70bff4d891d827f5",
          "sha256": "874fdf929f31222feff67307b3cfc3772cff5c3768c246af3226c62140ddcb29",
          "sha1": "ac88de177b6b6371129aac5087c1e947c73ee143",
          "md5": "c24b8a34658c8693bb9c20a3f176da04"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.24.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.9.aar",
          "url": "livekit-android-2.24.1.9.aar",
          "size": 4138784,
          "sha512": "40f8c21447527f73eb077d3ef2fa9e31f1987d9a86be2bfdc6c29eafa2b3bb03fc4cab355a75c42ff59cb800686ed5d9451953290dd7210a70bff4d891d827f5",
          "sha256": "874fdf929f31222feff67307b3cfc3772cff5c3768c246af3226c62140ddcb29",
          "sha1": "ac88de177b6b6371129aac5087c1e947c73ee143",
          "md5": "c24b8a34658c8693bb9c20a3f176da04"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.9-sources.jar",
          "url": "livekit-android-2.24.1.9-sources.jar",
          "size": 1034047,
          "sha512": "72b578c85b3a329b78d70d00a187315c7bb7fb6df0f80ff6eb409453453c374b41b262e4730e9d365a0a3bddb6c5dc702c6ed3f4d7ec4efc519ff3a09410eab3",
          "sha256": "92828420bccb46de6a705b4ed8a8bf699d8510ed57a0e6bdc572ea9f63f942a3",
          "sha1": "ebf36c921a85fb598d47105f365eeadddfed0143",
          "md5": "841995bec858f161e9b5766d69e138a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.9-javadoc.jar",
          "url": "livekit-android-2.24.1.9-javadoc.jar",
          "size": 7490118,
          "sha512": "e5921fa57a971696ad54e20c8c1ecdc613503a8da6fc4294d10751015d6c6b4df92431d8f454ada87427c1302e1f661460d33726afc4e3361f4908b0a8461b8c",
          "sha256": "6733b35f30d76bebc17827c5ce200bf77593471aece334266b9e38a01f23adfc",
          "sha1": "d7777eec58246ae483392ec73823b4cdc2e5f0b9",
          "md5": "2b03cde32e5b727e5c7c0a6cdc26ae90"
        }
      ]
    }
  ]
}
