{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "ttsignal",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ttsignal-1.0.5.aar",
          "url": "ttsignal-1.0.5.aar",
          "size": 2606969,
          "sha512": "34dded2b2f7eb11944a95ce2023142b2023bc28656040809acfa7bf09965eb5ebc7664f089566078504712d774c7ac0d18d0a61597594a1f681229e15f08fada",
          "sha256": "ba6ba80fd3ef354740a5a4f46723e61f4d3336d18904d98fcaa2081a24c05795",
          "sha1": "0b0fd576a1d28a773430837a16d5f5fc14302a59",
          "md5": "32919cbf28029d8102f97fe97e3d517c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "ttsignal-1.0.5.aar",
          "url": "ttsignal-1.0.5.aar",
          "size": 2606969,
          "sha512": "34dded2b2f7eb11944a95ce2023142b2023bc28656040809acfa7bf09965eb5ebc7664f089566078504712d774c7ac0d18d0a61597594a1f681229e15f08fada",
          "sha256": "ba6ba80fd3ef354740a5a4f46723e61f4d3336d18904d98fcaa2081a24c05795",
          "sha1": "0b0fd576a1d28a773430837a16d5f5fc14302a59",
          "md5": "32919cbf28029d8102f97fe97e3d517c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-1.0.5-sources.jar",
          "url": "ttsignal-1.0.5-sources.jar",
          "size": 5920,
          "sha512": "f6aec82125a9988541f4daf27a0cc3f21d4eb371194c8a6986fe58f6d9c7d0554e49fb4d0379a54b3826c9f565631cd26cc59c981d69fee931553457e7372772",
          "sha256": "cb297a753cfda9aeffc67247d0485069f9fc01c45d4476ca9e9fdaf56f2be8b3",
          "sha1": "79ff75c5e0fcfd79b1473faec174f624e2cd6eac",
          "md5": "7766825a4e18ebe9e572df0d5d25e488"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-1.0.5-javadoc.jar",
          "url": "ttsignal-1.0.5-javadoc.jar",
          "size": 296371,
          "sha512": "cce63a7b106601084b505a944504e15de245ccd842611b0520da5b028775b44c3c1bf4e86948ed00d9554edf19415f8f94a1c7e16247140c2084d841a9e3f7f3",
          "sha256": "ad2d879237a6e297d1868e6621bce7043ac748953a5afccdd1c0e4746e87ce56",
          "sha1": "9cf6edbe8557436495bea8ee5917db55b6795f90",
          "md5": "13e12b1ef798ab2f934ca3ffb4953a2c"
        }
      ]
    }
  ]
}
