{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.24.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.18.aar",
          "url": "livekit-android-2.24.1.18.aar",
          "size": 4156447,
          "sha512": "fa7a14c3a9b13739c85c1b07b327af5abdebfa01b4f35bac015de03ca8123af070a986db3f93bd5f0cb4cec1b03b662fda56c9b8534ee3de285a47eb21845c22",
          "sha256": "5b425aa135fefe0794a4af4411a126fa0e293e93bfe6537b15e49ee598497f1c",
          "sha1": "ea36a5647353b68c6437e9d97d95514d266054b8",
          "md5": "9f73295f3bd95bdfa536b6d455a41c22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.24.1.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.18.aar",
          "url": "livekit-android-2.24.1.18.aar",
          "size": 4156447,
          "sha512": "fa7a14c3a9b13739c85c1b07b327af5abdebfa01b4f35bac015de03ca8123af070a986db3f93bd5f0cb4cec1b03b662fda56c9b8534ee3de285a47eb21845c22",
          "sha256": "5b425aa135fefe0794a4af4411a126fa0e293e93bfe6537b15e49ee598497f1c",
          "sha1": "ea36a5647353b68c6437e9d97d95514d266054b8",
          "md5": "9f73295f3bd95bdfa536b6d455a41c22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.18-sources.jar",
          "url": "livekit-android-2.24.1.18-sources.jar",
          "size": 1041012,
          "sha512": "a535e438344dc130cd7868f0b8a4f1318a00d1a07ed5cb58bfd2a83857cb6baa39f1945c94a6f8e37422d79649e843aeb0b23c525b4f9e4d2caf31a838ac0416",
          "sha256": "1bae68ad238367f7142258ada02720de0108dae40f6ce11a1485c20970c51497",
          "sha1": "606554c0b8ee3ff0d07f4c7acdc250b8a1d1f186",
          "md5": "9e52630a82b2aafd6ab8641453128032"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.18-javadoc.jar",
          "url": "livekit-android-2.24.1.18-javadoc.jar",
          "size": 7511103,
          "sha512": "d206c4bf19b285d70803ccabcb56ec4b5c893b2014ce1c511d95b55642be61e708f748c59573e57cf890c5402109a5b1cdf1dff736dc9102500d0e7f945755f7",
          "sha256": "795000c5b9b932bc21f21200528f076ff46b737b0ab97f158ecef2b266ed576c",
          "sha1": "1547780836695e87609a0eee6c3bf6732e790166",
          "md5": "4e2c2b3ac5f855ff023a67375026d8ea"
        }
      ]
    }
  ]
}
