{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.27.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.8.aar",
          "url": "livekit-android-2.27.0.8.aar",
          "size": 2888574,
          "sha512": "c603facd4d9441fd7a5e35a80f78eeec68b2c2997870d28ec09f8139de0754f8472cad6aef4d581675320a8a5bf218568fbd42f2ec950a70dd00a370c7337c9a",
          "sha256": "2a76648e153400c83616c6f3ca84395862f31475c7c70ccbda78c5e01d23c833",
          "sha1": "d6bce215dc3bfea316294a0b92c4a9b7b0ace043",
          "md5": "43dfd47da60d4c8fc4ae10a88921ce09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.27.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.8.aar",
          "url": "livekit-android-2.27.0.8.aar",
          "size": 2888574,
          "sha512": "c603facd4d9441fd7a5e35a80f78eeec68b2c2997870d28ec09f8139de0754f8472cad6aef4d581675320a8a5bf218568fbd42f2ec950a70dd00a370c7337c9a",
          "sha256": "2a76648e153400c83616c6f3ca84395862f31475c7c70ccbda78c5e01d23c833",
          "sha1": "d6bce215dc3bfea316294a0b92c4a9b7b0ace043",
          "md5": "43dfd47da60d4c8fc4ae10a88921ce09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.8-sources.jar",
          "url": "livekit-android-2.27.0.8-sources.jar",
          "size": 647331,
          "sha512": "41d7584327c575c39cdd5186308e82fe9e039f8a62d4d1a58d2e46dabd59c7aa575db7711a38fa4dee6f9682664bfc143b7931c7eea81b77f8aea1487e39a6f3",
          "sha256": "0757c4f7de8b5d2d7ab94d43336ef3303783f27575a6869dee4606bd13ceabbc",
          "sha1": "da663b9a551d521cc69c04ed2c7757121f81023e",
          "md5": "146fb1923bb14fe5849658da795c34f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.8-javadoc.jar",
          "url": "livekit-android-2.27.0.8-javadoc.jar",
          "size": 4127782,
          "sha512": "2e3dc01e12cfbfd2104f7a533e66cbd1ec5ad0f2ac1def050aff5b0ccb4029ae0147d349151bf56dca6abafc75f8598cb31bbba73a3b2516724b5eb634fa6de2",
          "sha256": "f2f016a38d972e789de9a2079b20e3b9c2bdfcc8b6aeb548c1e475f0e1609483",
          "sha1": "d87a54659942a116483560082aaeb98c70c86bc2",
          "md5": "3e33771a9c897e340f94b4711c80ee6b"
        }
      ]
    }
  ]
}
