{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.5.aar",
          "url": "livekit-android-2.23.5.5.aar",
          "size": 4057341,
          "sha512": "48396352e828cb2c63b85215f4aec4036801b91962faac2818f0951f23883f7207a06a974ed29b2a06f8bf621e30310c947e999ff6a8cbff87b99f43e03e6ec3",
          "sha256": "eaeb0848d4e1f9052e5239e712b078fd60e3a80a8230c7cf4f7567347e8b1d8f",
          "sha1": "1ddb4e46b2566d1d8e6693cd43562708801f3049",
          "md5": "4899dd0d4d605a93aececd6248c98cf2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.23.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.5.aar",
          "url": "livekit-android-2.23.5.5.aar",
          "size": 4057341,
          "sha512": "48396352e828cb2c63b85215f4aec4036801b91962faac2818f0951f23883f7207a06a974ed29b2a06f8bf621e30310c947e999ff6a8cbff87b99f43e03e6ec3",
          "sha256": "eaeb0848d4e1f9052e5239e712b078fd60e3a80a8230c7cf4f7567347e8b1d8f",
          "sha1": "1ddb4e46b2566d1d8e6693cd43562708801f3049",
          "md5": "4899dd0d4d605a93aececd6248c98cf2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.5-sources.jar",
          "url": "livekit-android-2.23.5.5-sources.jar",
          "size": 1017158,
          "sha512": "8b819e312c953f619e0726c88f3aa79ba7fcbcfd87e31761bb8479d08323dfd6bfba8d7d5900da29f18c5a540f562b6f0e0bcbdefa07366ef0eec771b4649037",
          "sha256": "b6addd78d9e8cfe02a665194241bc585462ed05c5bf0f99568c414f9c923d9ac",
          "sha1": "46770af6065a0aa12ae0f2d9b3eefbbe2f78a764",
          "md5": "ee0b029818cc3a82b55d0c561333677a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.5-javadoc.jar",
          "url": "livekit-android-2.23.5.5-javadoc.jar",
          "size": 7474736,
          "sha512": "4385767c31aec21f4688be2a3386b58e485ab9736a436bf51b68df0f406b5d070c970e222a1c8682b90dd33adea51b7e29732a80453819525b36c70542c2ad05",
          "sha256": "3c97d031607bcadd7b79d03ba2b5e0a10204d2a7025452efc1a0348662358be3",
          "sha1": "223487967529b138c6809124c41ee667b66d0a1d",
          "md5": "0f7dc952e5106b7d723e5a86e4d6821f"
        }
      ]
    }
  ]
}
