{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.18.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.1.aar",
          "url": "livekit-android-2.18.3.1.aar",
          "size": 3408672,
          "sha512": "6d5be0659cc37bea5cc75c4c6f6126375c07858faefda3b49b3b519889749e4c03cf5e5252ef6207439cbafa844224287783c3ce77f60c5f78852089daa56dae",
          "sha256": "636d4ed574da93c85b3b85bfc1459959b4079819854a081f1cd93f5002e32744",
          "sha1": "57c909cb82c364d447b32514022aed8826af8040",
          "md5": "5e21183a7e28d37fcf4bb016205d1eb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.1.aar",
          "url": "livekit-android-2.18.3.1.aar",
          "size": 3408672,
          "sha512": "6d5be0659cc37bea5cc75c4c6f6126375c07858faefda3b49b3b519889749e4c03cf5e5252ef6207439cbafa844224287783c3ce77f60c5f78852089daa56dae",
          "sha256": "636d4ed574da93c85b3b85bfc1459959b4079819854a081f1cd93f5002e32744",
          "sha1": "57c909cb82c364d447b32514022aed8826af8040",
          "md5": "5e21183a7e28d37fcf4bb016205d1eb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3.1-sources.jar",
          "url": "livekit-android-2.18.3.1-sources.jar",
          "size": 872377,
          "sha512": "81405e749f9baf48db3d2952c5803fd6642a79695557acd81f1fcc20f6da4b732d2472466df952f1c6abb17769924d671832f39fab0da8311aec1b7a467a4112",
          "sha256": "b0d9c7cd6abc480a3e4e1e9bac8af402d9e5f5a4271f5fbaa18326d63fb6c7f6",
          "sha1": "0316e404645aa9490cf8c6221f6103d78d9f7165",
          "md5": "94fb82cd05a36a2180ee58f70b187f0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3.1-javadoc.jar",
          "url": "livekit-android-2.18.3.1-javadoc.jar",
          "size": 6521576,
          "sha512": "467bbc335f1bba757fa2dffba2c77ed81847fbd953673ef3346900d62aa174856cbc8a9cc3582be325a144c6ebced9cc8a27aba90af4984f315acfb368dfb073",
          "sha256": "aaf94d29353de85b54a487eca0bd6c790f576ef5f5da5f6adf35a6abeaf11c56",
          "sha1": "3a94d1c5ca34f6138dd0d2d932c868247932c09b",
          "md5": "710b45860ba335b87f395144c7033c09"
        }
      ]
    }
  ]
}
