{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.27.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.5.aar",
          "url": "livekit-android-2.27.0.5.aar",
          "size": 2888470,
          "sha512": "4761984fd60e80441796ec0426c2ab1a72913dc5bf7deba5064fd056a8f23f327be83ddd9f95c5686ee8bb00753edd7c91ea8110e740efbf2ccec723d50f7822",
          "sha256": "6d2ded37b98b117958a8ed9475d29963726817533a11a79e21408fc99e183bff",
          "sha1": "007a2058462d136784deea0e02ff4e61b363ea30",
          "md5": "0dc793cb30c73096a4008e0bba476f92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.27.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.5.aar",
          "url": "livekit-android-2.27.0.5.aar",
          "size": 2888470,
          "sha512": "4761984fd60e80441796ec0426c2ab1a72913dc5bf7deba5064fd056a8f23f327be83ddd9f95c5686ee8bb00753edd7c91ea8110e740efbf2ccec723d50f7822",
          "sha256": "6d2ded37b98b117958a8ed9475d29963726817533a11a79e21408fc99e183bff",
          "sha1": "007a2058462d136784deea0e02ff4e61b363ea30",
          "md5": "0dc793cb30c73096a4008e0bba476f92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.5-sources.jar",
          "url": "livekit-android-2.27.0.5-sources.jar",
          "size": 647201,
          "sha512": "f9691f7c2bfefdcac84660cfc91e80a40184bc8f2486a5241b71f4e97f506d3e06acfd7dd7a7c1939c5c148b2645db196240725037f74228a1132f86cc96c253",
          "sha256": "3756e6c04cc487b563024f0fc58c429cb124cd3e534fcf31f022bff900f33b91",
          "sha1": "c1ea2a36387b284e1d76a8a4c9432c26a362d760",
          "md5": "71871737ba5c763c81b0960be54b382e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.5-javadoc.jar",
          "url": "livekit-android-2.27.0.5-javadoc.jar",
          "size": 4127438,
          "sha512": "2bebc89699928952ae97bf26b4d6df3e5622c54c687908e8af7d18e7c7c0bf461be0f04533c0a8413ff3607223046bea84e95c1d530c9029bc510d925c895448",
          "sha256": "a23a809ca0d7955878f6d01f058864bc1a6bebc56a797f270290a52f8bcd1389",
          "sha1": "cd98d4c2ea9e1a22324f2eee3170248643e39910",
          "md5": "4283f64b40f2a580b21afac0d9ba082c"
        }
      ]
    }
  ]
}
