{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "dtproto",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "dtproto-3.1.0.aar",
          "url": "dtproto-3.1.0.aar",
          "size": 1099830,
          "sha512": "66c61486b5b46058cb470cbee2c57371b7ca63a1c27bb6e44a2d7c42f38aaf2c7b58d600e91f7d0c510ce58d1fefdcc1bdff7eb74de3224be7c760e75a6dd0be",
          "sha256": "7a086d004729434fab67f18d0847b31534853d3aa4873043c1dead4c597aed00",
          "sha1": "f1be4ebc048756fc8dbffefb6748fe12fed14c5f",
          "md5": "44e174e21d957e683a903b9212d81574"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "dtproto-3.1.0.aar",
          "url": "dtproto-3.1.0.aar",
          "size": 1099830,
          "sha512": "66c61486b5b46058cb470cbee2c57371b7ca63a1c27bb6e44a2d7c42f38aaf2c7b58d600e91f7d0c510ce58d1fefdcc1bdff7eb74de3224be7c760e75a6dd0be",
          "sha256": "7a086d004729434fab67f18d0847b31534853d3aa4873043c1dead4c597aed00",
          "sha1": "f1be4ebc048756fc8dbffefb6748fe12fed14c5f",
          "md5": "44e174e21d957e683a903b9212d81574"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dtproto-3.1.0-sources.jar",
          "url": "dtproto-3.1.0-sources.jar",
          "size": 10855,
          "sha512": "c2ee73522e1e5325aeec2a4beb846303f2274496bc17ce3539c25c50cb83d76618f3861f02955a6c993902e4d82382439f4c54c34a52e5468aef6b01f7597ba3",
          "sha256": "db3fe3bfaf2c138e2daf618cad310bd017bb95e34acc223c210640282fabc4cc",
          "sha1": "9b120f4e9844cd80c592ae7af50091af03f6abb3",
          "md5": "a9508cf98a1a2b9ba06cdb11559ad45c"
        }
      ]
    }
  ]
}
