{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "dtproto",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "dtproto-3.1.0.aar",
          "url": "dtproto-3.1.0.aar",
          "size": 1106650,
          "sha512": "dc237b3f42f1ba55b71f42f0dfa0366a1a3a68e8a1644a419d6a363b061618e360e8e7b5cf0fd6076d6cc552706190eb62854e6ce4e90125bda726ac55768717",
          "sha256": "abba5a26706ac19235f2ccdf01bf1731b5462740de5c74f52855c2f1cddddbb1",
          "sha1": "e6c91dea15a3eb578601f151cd5139aa8b518616",
          "md5": "168fc99d0cbe02049a26b73de1a7a3b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "dtproto-3.1.0.aar",
          "url": "dtproto-3.1.0.aar",
          "size": 1106650,
          "sha512": "dc237b3f42f1ba55b71f42f0dfa0366a1a3a68e8a1644a419d6a363b061618e360e8e7b5cf0fd6076d6cc552706190eb62854e6ce4e90125bda726ac55768717",
          "sha256": "abba5a26706ac19235f2ccdf01bf1731b5462740de5c74f52855c2f1cddddbb1",
          "sha1": "e6c91dea15a3eb578601f151cd5139aa8b518616",
          "md5": "168fc99d0cbe02049a26b73de1a7a3b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dtproto-3.1.0-sources.jar",
          "url": "dtproto-3.1.0-sources.jar",
          "size": 11014,
          "sha512": "99223bc34df542a16ba0b10e55e9bff69177c6face473f1542f15ce7006b77975c29344a1e316381e955486fdae2b8c9074c6c6bc8d83a6ac77df524b89ae698",
          "sha256": "76d3e4feb4c44c6b7c4360b48e667f1799b280ee48d4d9a550a4001e51351f1a",
          "sha1": "5510dad0d0220e298f617c362e8f0e0e9865056c",
          "md5": "04d4434ec778f5087389380e2710bdf1"
        }
      ]
    }
  ]
}
