{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "audio-pipeline",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "audio-pipeline-1.0.12.aar",
          "url": "audio-pipeline-1.0.12.aar",
          "size": 69669193,
          "sha512": "a4cc2c299b81ff0280cf229896ece054953d4d7bb23adac024539ecd3c889400765b80016eb89744dca553d9badabc5307e3ee2bc25d64d4c58c092916a0732c",
          "sha256": "777b112fbd0a18f7db5522fe7d3917e2561d26a7337fce4082763e4bd16b4869",
          "sha1": "080ed82754369be1d19ce730bc081222e5f35fbc",
          "md5": "ebc07b70b8e776ec3a9a97ce7a8718b8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "audio-pipeline-1.0.12.aar",
          "url": "audio-pipeline-1.0.12.aar",
          "size": 69669193,
          "sha512": "a4cc2c299b81ff0280cf229896ece054953d4d7bb23adac024539ecd3c889400765b80016eb89744dca553d9badabc5307e3ee2bc25d64d4c58c092916a0732c",
          "sha256": "777b112fbd0a18f7db5522fe7d3917e2561d26a7337fce4082763e4bd16b4869",
          "sha1": "080ed82754369be1d19ce730bc081222e5f35fbc",
          "md5": "ebc07b70b8e776ec3a9a97ce7a8718b8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "audio-pipeline-1.0.12-sources.jar",
          "url": "audio-pipeline-1.0.12-sources.jar",
          "size": 4711,
          "sha512": "313008fda52ea46c454aca0d8d5524ccbfbf68370c54b378b1b2eb7afc10f0f943367300edcbe8c61f041adc3ceded4a98bdf59ff033da9204445bb0003197d2",
          "sha256": "43bb0d3a78fa23d6de46c11356630aa3f06c1a6fc36cc6393b64d803f6ef5c19",
          "sha1": "6d98bbaf5bd18769f98297c836331bb790b26983",
          "md5": "950d7eccc9a896fb9355ff1b33d8348e"
        }
      ]
    }
  ]
}
