{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.8.aar",
          "url": "livekit-android-2.23.5.8.aar",
          "size": 4058403,
          "sha512": "6b689e560bb19dececc48265acb2caa3c3ccc07e428fe86305d88fca330da846b87b0c75d8fb0f2d985c01c297b8415f25578b595ca08a71885ff4b9c29cc421",
          "sha256": "603aca2f9d36e60119cadb710ac9914dd0f739e40e07f928a89062f269ce9487",
          "sha1": "0fb73b34f37c3b2ed09b17c7d19044d18841e5f3",
          "md5": "1c86ac535d8f323431121afe9ab7aca7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.23.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.8.aar",
          "url": "livekit-android-2.23.5.8.aar",
          "size": 4058403,
          "sha512": "6b689e560bb19dececc48265acb2caa3c3ccc07e428fe86305d88fca330da846b87b0c75d8fb0f2d985c01c297b8415f25578b595ca08a71885ff4b9c29cc421",
          "sha256": "603aca2f9d36e60119cadb710ac9914dd0f739e40e07f928a89062f269ce9487",
          "sha1": "0fb73b34f37c3b2ed09b17c7d19044d18841e5f3",
          "md5": "1c86ac535d8f323431121afe9ab7aca7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.8-sources.jar",
          "url": "livekit-android-2.23.5.8-sources.jar",
          "size": 1017739,
          "sha512": "7376730bf6ebaaef0f878374495bb3aabd138d48541dca9a363db0f4141442b069a4b1b13f8cd8778e10973a9c6ed57186795258ac92eb739416834256e7cc56",
          "sha256": "668a772e9130cc027dd09fd28e104f63d00b965e93520f960403060152421111",
          "sha1": "2250c33799ecbf0b1cae5abc12243963c557fab3",
          "md5": "34817de0514004849fd611bb209aba65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.8-javadoc.jar",
          "url": "livekit-android-2.23.5.8-javadoc.jar",
          "size": 7432823,
          "sha512": "4bf7c04871ebaa99ab8c52a5885c275900e4c67ae3dbb84b0be6a39297b09341fbcbf96481fcd1bfa14c46907f26db9edd800bc95d17e208eaa536484ea22979",
          "sha256": "c8f70f6c677edf7f115fb269ea70aa4e193856bb268930371a0d2abb3c972de4",
          "sha1": "53d676f72763b35eb8addb082145161141d0bc55",
          "md5": "5607bb7650d66a8ac0a346e870e0d03f"
        }
      ]
    }
  ]
}
