{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.1.1.aar",
          "url": "livekit-android-2.23.1.1.aar",
          "size": 4004273,
          "sha512": "40b8475dfdc02d5ce6b6000e4383898cc0cdfb6399502fec9fbcb0c5452f7c3387eb29246190a27b4c37f897adc356abad146093a90e4dd5ddbe79f05a286deb",
          "sha256": "4c4ebf07778260b15d6d1eaec6ee0b653fcf777059ef1f9981bcaeae42bea819",
          "sha1": "7aced0674d94282e348e8cdac15d35f08ac58dd4",
          "md5": "b11cde437e28eaf731f0a4c894ba7736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.1.1.aar",
          "url": "livekit-android-2.23.1.1.aar",
          "size": 4004273,
          "sha512": "40b8475dfdc02d5ce6b6000e4383898cc0cdfb6399502fec9fbcb0c5452f7c3387eb29246190a27b4c37f897adc356abad146093a90e4dd5ddbe79f05a286deb",
          "sha256": "4c4ebf07778260b15d6d1eaec6ee0b653fcf777059ef1f9981bcaeae42bea819",
          "sha1": "7aced0674d94282e348e8cdac15d35f08ac58dd4",
          "md5": "b11cde437e28eaf731f0a4c894ba7736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.1.1-sources.jar",
          "url": "livekit-android-2.23.1.1-sources.jar",
          "size": 1004543,
          "sha512": "f38df75e4200011e9fb4d9540596b7734d5dc4647a985508acd0a7e2da3e3b79b70e9611521160cf4cf4400a2316cf57a11e5589a9280471ed321e5b64476626",
          "sha256": "9032a30793c3b51a009f555250f341e2295a80451116e62efde3b091436eb80e",
          "sha1": "4cf10cb6c5a908851ae4d90de8c71c47aca2f12b",
          "md5": "ed79a42aff1ddbdefb11a41bb6313773"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.1.1-javadoc.jar",
          "url": "livekit-android-2.23.1.1-javadoc.jar",
          "size": 7465195,
          "sha512": "bfc9d8a4ef8458e6632a317da76415d2a9256e12a4f9d0650971362dc184689051d1e5dbff42c3153e896273ebe5f944af2fbe64f52fd782e8a360f73837ad17",
          "sha256": "44109548e3cd5081ba2e34fbbb465e5e53af4ad9c4a13ca1c3f0b9d5e22f52ff",
          "sha1": "93c37e4d913e147ddb9a3409654521f4e3861a18",
          "md5": "b6bad18810feeb587193a450991ef6c1"
        }
      ]
    }
  ]
}
