{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.3.aar",
          "url": "livekit-android-2.23.5.3.aar",
          "size": 4048553,
          "sha512": "b728d10a7558f0a57b6fab47287cbac567e50520bf57b1fbe5db1172747ef022837283193f979ec48bb652ea9f93c9e980195c8e00585f11fa97cfc4f5de7dc2",
          "sha256": "abec89991a56d54b00b075a806707eca4078cc8239a71f7da49f6be2c5e27f3b",
          "sha1": "15c9908366c50a4c2653f7d6cd5cfeb15548539b",
          "md5": "73576550e34c535446e0e4f17f8ac705"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.23.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.3.aar",
          "url": "livekit-android-2.23.5.3.aar",
          "size": 4048553,
          "sha512": "b728d10a7558f0a57b6fab47287cbac567e50520bf57b1fbe5db1172747ef022837283193f979ec48bb652ea9f93c9e980195c8e00585f11fa97cfc4f5de7dc2",
          "sha256": "abec89991a56d54b00b075a806707eca4078cc8239a71f7da49f6be2c5e27f3b",
          "sha1": "15c9908366c50a4c2653f7d6cd5cfeb15548539b",
          "md5": "73576550e34c535446e0e4f17f8ac705"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.3-sources.jar",
          "url": "livekit-android-2.23.5.3-sources.jar",
          "size": 1010778,
          "sha512": "42ebc4026fd7081c8169e8011391f865e5c19947df84cc75078e9629bf721c151f918afbe7a08cc28aa5b5f41d29c4a5073fb64beff78c7d5dec38d3cc6499be",
          "sha256": "78b76c0727b992a9630576d63319bfb83e9ff2289bd89900c02d32b7a124dd25",
          "sha1": "0fc115e95790a94824e8f96775e93d317714bb14",
          "md5": "b3ea3242fdaaf075580f8886ce192505"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.3-javadoc.jar",
          "url": "livekit-android-2.23.5.3-javadoc.jar",
          "size": 7473093,
          "sha512": "d29928a5d7551d894b873817bf2e3adc1c64263ed53e2cf0c42dd376368766d72c221e7e8053ad92829c0cea8cc66dbc8e785840e04564bf81ef488b2c6c397b",
          "sha256": "70ec73bb91127bf18e88be0ba0690679350fa9d5a376fc089c927e2f9086c17a",
          "sha1": "5a90d04dbe6e4a8994339a9e8ef21b0a67e1a860",
          "md5": "3aef31e927d10cbc445db4b2959435db"
        }
      ]
    }
  ]
}
