{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.18.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.18.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.18.3.4.aar",
          "url": "livekit-android-camerax-2.18.3.4.aar",
          "size": 45523,
          "sha512": "826b7a2d9fd3e5284e408586802c1f34a4a5ae26c07b8b23a13ae0f296591141004e607b8172ad3e5369e3cc35dde8f23747799f36b75b0c39e65cbb49b49894",
          "sha256": "69f86d0d576a5687cee9c8f70506ae7bc31ec418579bd72ac6906d15a75f79b3",
          "sha1": "7ae9bf199aacbf35def3f65fcad887d34b39bfe7",
          "md5": "7857f16c4279192bfd2436b3b0548bc2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.18.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.18.3.4.aar",
          "url": "livekit-android-camerax-2.18.3.4.aar",
          "size": 45523,
          "sha512": "826b7a2d9fd3e5284e408586802c1f34a4a5ae26c07b8b23a13ae0f296591141004e607b8172ad3e5369e3cc35dde8f23747799f36b75b0c39e65cbb49b49894",
          "sha256": "69f86d0d576a5687cee9c8f70506ae7bc31ec418579bd72ac6906d15a75f79b3",
          "sha1": "7ae9bf199aacbf35def3f65fcad887d34b39bfe7",
          "md5": "7857f16c4279192bfd2436b3b0548bc2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.18.3.4-sources.jar",
          "url": "livekit-android-camerax-2.18.3.4-sources.jar",
          "size": 23285,
          "sha512": "b21524a80854e8c00a5f4213044fd4eb8315f8315b966f39fa4d9bde0506766c747d6eba3c85e779233fabff10e9a19b79b6097ac6deaf2122ea883ec43450bd",
          "sha256": "f108c96a36d3d7025ec7e8491e405f2f9616460698f37446b34db8ab02f668fd",
          "sha1": "eb4cdeced06d21f374f996c6bce74746e8f6ca55",
          "md5": "92e9e76684b74193ddaef43386c7d243"
        }
      ]
    }
  ]
}
