{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.13.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.7.aar",
          "url": "livekit-android-2.13.1.7.aar",
          "size": 2940287,
          "sha512": "6ca61bf17314bcfb8b9c8e218c0a08b908d1c220cd7d25cfdf45936fb7d2fd4f5516fadfc106eff8f8bcbbfc52919d9f034c0c9ba7dbba69a2c71528e1bfdfee",
          "sha256": "c6ef1435b05aab4637f146e892e75bd30651d8fe9d137cbebd78d1b33c62bd10",
          "sha1": "303074054ebb10006f6422d9896366b3d37bfd7f",
          "md5": "1028a82fd5ffb1e0dc8d2e6f9a423102"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1.7.aar",
          "url": "livekit-android-2.13.1.7.aar",
          "size": 2940287,
          "sha512": "6ca61bf17314bcfb8b9c8e218c0a08b908d1c220cd7d25cfdf45936fb7d2fd4f5516fadfc106eff8f8bcbbfc52919d9f034c0c9ba7dbba69a2c71528e1bfdfee",
          "sha256": "c6ef1435b05aab4637f146e892e75bd30651d8fe9d137cbebd78d1b33c62bd10",
          "sha1": "303074054ebb10006f6422d9896366b3d37bfd7f",
          "md5": "1028a82fd5ffb1e0dc8d2e6f9a423102"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.7-sources.jar",
          "url": "livekit-android-2.13.1.7-sources.jar",
          "size": 778949,
          "sha512": "775c2ab6e19bca528fea6c2fdb2e87c5a12da213fff45307d2127e925c54e379b1bb825bdf6588fc508ddfe6fce0ad5704d461b6ea36b0783524ea813beabca2",
          "sha256": "3bb32389aeeb4f00945e3d368bd84af23eb9fb796e13b8ea516c0e3bd0399cb3",
          "sha1": "9e01d601799e9377e326e9da1836733f9d52f4a2",
          "md5": "54b9942c27e4eff4747edb717ce29717"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1.7-javadoc.jar",
          "url": "livekit-android-2.13.1.7-javadoc.jar",
          "size": 5758428,
          "sha512": "7410f7a0d2ce300b9520d3c86fd1f2ee466d8dc764fecaa33fe4bc406a1b3b8bfebf2f34e24e4f35aa61d78a3c7843b5a9ebf30c4b974b611dae23e94123cf45",
          "sha256": "80e85a1a8ac3e1be77656780bf509933d0cc496e1a6849cbebb09ef96c6e97f7",
          "sha1": "dd71ecb8fb80f4afb6e9b7c646400da6baadf6d9",
          "md5": "0ffca5ce5be26e9867d32d8699c6335a"
        }
      ]
    }
  ]
}
