{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.aar",
          "url": "livekit-android-2.22.0.aar",
          "size": 3935420,
          "sha512": "50cffd3c724960697d42757eb48dbf77d87c523921e5df413ce40dc97da72e782656f9d2703d9af8722b94c479d2939c055f5020c10499d8c3523e5d16020f37",
          "sha256": "2e5ac212b3c83ce26f27505ec2c11653598241a97c5c898646fbd23cb3c62c3d",
          "sha1": "6bd751e74094073434a5fc7d017c2548bdf21c81",
          "md5": "a8f635f411fe74e0366eebdf66260ba5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.aar",
          "url": "livekit-android-2.22.0.aar",
          "size": 3935420,
          "sha512": "50cffd3c724960697d42757eb48dbf77d87c523921e5df413ce40dc97da72e782656f9d2703d9af8722b94c479d2939c055f5020c10499d8c3523e5d16020f37",
          "sha256": "2e5ac212b3c83ce26f27505ec2c11653598241a97c5c898646fbd23cb3c62c3d",
          "sha1": "6bd751e74094073434a5fc7d017c2548bdf21c81",
          "md5": "a8f635f411fe74e0366eebdf66260ba5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0-sources.jar",
          "url": "livekit-android-2.22.0-sources.jar",
          "size": 1000247,
          "sha512": "6d6777facd34e19b86ec3d73f6d03de9f325b8745d161e9e8113be60b30d31c86be78b85af7d8729f4cc3ee97c293a5a1b7584999b06f8c8c4b36858a1b08a2b",
          "sha256": "cb32b3dd4738ca4a3af5d7b67208195b25b87a6feca6d481fe7d8d37920d2571",
          "sha1": "39e766f6d48e156644b0559d2ece01daabb9a774",
          "md5": "79bb2918eac7469c502c8afb20810ca8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0-javadoc.jar",
          "url": "livekit-android-2.22.0-javadoc.jar",
          "size": 7445146,
          "sha512": "cd08333ce88df98758235f431bd5344f6ec89566c484d9220aa9a8d9f2eab473c7b610a2798d60f0d9b3a268d453c6d6d1861c2122a14aa465ed8246481c9414",
          "sha256": "9517af3310534b94aced6c0019f9c10ad0cc67f67d3907e1b8ed8243907b278a",
          "sha1": "6250c8fc71f59540289642b54b212f481a5d9f20",
          "md5": "de6c566e336502431aef23820fbddfe9"
        }
      ]
    }
  ]
}
