{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-track-processors",
    "version": "2.24.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.24.1.11.aar",
          "url": "livekit-android-track-processors-2.24.1.11.aar",
          "size": 41856,
          "sha512": "ea9845cbe9b399e55e48927beb39f6ddb79df2784e52b5b7085f414345064a6533f0c7063e68399c75600a41b7b1b9e7584448aa4491ad0b89d85312d77a3d2b",
          "sha256": "68fa10b999a3a7e10b5313edb712da9f46d1fb48e965037060b940f74da2d375",
          "sha1": "f42393d88905b36126feb704491a46b00b9354a8",
          "md5": "84d120f404ff88efa92476ac370fe8fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.24.1.11"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android-camerax",
          "version": {
            "requires": "2.24.1.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "segmentation-selfie",
          "version": {
            "requires": "16.0.0-beta6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.24.1.11.aar",
          "url": "livekit-android-track-processors-2.24.1.11.aar",
          "size": 41856,
          "sha512": "ea9845cbe9b399e55e48927beb39f6ddb79df2784e52b5b7085f414345064a6533f0c7063e68399c75600a41b7b1b9e7584448aa4491ad0b89d85312d77a3d2b",
          "sha256": "68fa10b999a3a7e10b5313edb712da9f46d1fb48e965037060b940f74da2d375",
          "sha1": "f42393d88905b36126feb704491a46b00b9354a8",
          "md5": "84d120f404ff88efa92476ac370fe8fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-track-processors-2.24.1.11-sources.jar",
          "url": "livekit-android-track-processors-2.24.1.11-sources.jar",
          "size": 17076,
          "sha512": "95912e8560d56ec2c73ddf373c27915c20bea04aa17888735c7638df126380da747eae770a77c099966e3aedf969b891a54b5f126ab9e561a16d5b6abb1404da",
          "sha256": "9303c0bf395f5d88e566b3aefa9579e98b3428170f96ee1d0fec41e85bc70672",
          "sha1": "67c673637480ecffef32e1304729098183a70fcb",
          "md5": "ef0ec9f34ed9435975c6eb5e4e0ac5a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-track-processors-2.24.1.11-javadoc.jar",
          "url": "livekit-android-track-processors-2.24.1.11-javadoc.jar",
          "size": 294537,
          "sha512": "dfd3faf5841efc2088925d7bfb7864128d2cdb2056cd1c6d8e31ea984facf3de73a404360ada47e26d3e7f5218292690164465d762f193fca25965746713653a",
          "sha256": "05f504f1dc1efde7b0b5fbfaabd6cdec063be3a16fd1a4843d20f0176fdc72f8",
          "sha1": "f030565c58694e5fb6bca3dc4ec7abae75d55574",
          "md5": "b8083292595d67a3e66ec80adac92c19"
        }
      ]
    }
  ]
}
