{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.4.aar",
          "url": "livekit-android-2.23.5.4.aar",
          "size": 4057319,
          "sha512": "053570853f690166701951f18356c3b030c583d82669f39d505cae3c68ecd71df31ae93884f39f7f3d5dc82c46a8b532da54e556fef048491502478382079cfe",
          "sha256": "0a549f3a07b42b750a5d2bfa8636a6c978f3023f5bf94ba1d27c6298158c5509",
          "sha1": "db2667473f680d274006cd707f6573602cc6ff27",
          "md5": "1dce47eb01c7725dfebeb430858dffe8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.23.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.4.aar",
          "url": "livekit-android-2.23.5.4.aar",
          "size": 4057319,
          "sha512": "053570853f690166701951f18356c3b030c583d82669f39d505cae3c68ecd71df31ae93884f39f7f3d5dc82c46a8b532da54e556fef048491502478382079cfe",
          "sha256": "0a549f3a07b42b750a5d2bfa8636a6c978f3023f5bf94ba1d27c6298158c5509",
          "sha1": "db2667473f680d274006cd707f6573602cc6ff27",
          "md5": "1dce47eb01c7725dfebeb430858dffe8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.4-sources.jar",
          "url": "livekit-android-2.23.5.4-sources.jar",
          "size": 1017156,
          "sha512": "05a671627c6e141efe8aa4e8d77dd84399939c3c9b7ee89882980ead57f10aec15385b57e7324751e7cbb5479e169259cf8b84a24d5f2c6615008d194f70a675",
          "sha256": "bf67d95ee6f4408cf00fabd05b3dcb577871e8421146953f91808c2c6224edb6",
          "sha1": "911bc0fc14bfe3032ad410fe4e529b33e44ea056",
          "md5": "d1cb2973b7b9bb0661c45d200f05a59d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.4-javadoc.jar",
          "url": "livekit-android-2.23.5.4-javadoc.jar",
          "size": 7474819,
          "sha512": "39a035ec1489fe287310e5c25553de6fe7471a622eeffa66a8aa49d81047370d97d3325f8c8959dbcbdc8e6103c2fc31bc2bf2676e1678f92a3311fdb380742f",
          "sha256": "22763480ccf2f2f2b63563e52f41a4c933c5ab79630c33f0c2892aeb6fdc3538",
          "sha1": "b6a88e65948d83d4d90803d4541d4ab170bcc58d",
          "md5": "524b2602b40823c7f7f727e4aa105354"
        }
      ]
    }
  ]
}
