{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.8.aar",
          "url": "livekit-android-2.24.1.8.aar",
          "size": 4127713,
          "sha512": "2b29f94360c3ad19deaa4e42da3812cd1a54e845dac986ad59c37462d00541dcb6a11fff5e8ffd4b156dee1a6d14fc331a4977b3907fba4332cc967e3ca89030",
          "sha256": "e9e1d0cff814d7c2d0e08befbc503b7cb54a5987c2a4baaf3c2f46038db8488c",
          "sha1": "33a939fe59d0b1795ace793062f145625723ebd6",
          "md5": "64067cb764729a3b92487d319f9fec9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.24.1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.8.aar",
          "url": "livekit-android-2.24.1.8.aar",
          "size": 4127713,
          "sha512": "2b29f94360c3ad19deaa4e42da3812cd1a54e845dac986ad59c37462d00541dcb6a11fff5e8ffd4b156dee1a6d14fc331a4977b3907fba4332cc967e3ca89030",
          "sha256": "e9e1d0cff814d7c2d0e08befbc503b7cb54a5987c2a4baaf3c2f46038db8488c",
          "sha1": "33a939fe59d0b1795ace793062f145625723ebd6",
          "md5": "64067cb764729a3b92487d319f9fec9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.8-sources.jar",
          "url": "livekit-android-2.24.1.8-sources.jar",
          "size": 1029985,
          "sha512": "e1a132d9c2a40d69a708993dcba4350aaa3a8cc9f4dde41d803ebea83e07bf6efc0efac4dad8caead7dc2e52cdc05a34f51b888bd1e7ffa5ac381e5220e1a285",
          "sha256": "d21508821197e7a139d3cb247828699c0f428b1a6a63e0d530f642d20072e3b2",
          "sha1": "26f3e54da6a60074110a59ca3e34864a114fa648",
          "md5": "74db63a431ea27fccd4dbaf649591e5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.8-javadoc.jar",
          "url": "livekit-android-2.24.1.8-javadoc.jar",
          "size": 7501533,
          "sha512": "8853cf96d71ce07ab9be2aba4129cab70b7f1a1cd039c756beba79edf8169d7732465d4ab78c2015b8349fd1dc5a4a5f724bce7844d6041acad4660d971b87a0",
          "sha256": "4512b1a62ec386dad061e3e95f43dbe214505ebfab9fd082a7e5ff779c90dc73",
          "sha1": "2cb15b1945043159648f239b59064906ba2e0383",
          "md5": "9d306b9c9b4de86836cd1e9213b7bc22"
        }
      ]
    }
  ]
}
