{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.1.aar",
          "url": "livekit-android-2.23.2.1.aar",
          "size": 4019288,
          "sha512": "4deede631d567394736a827e58faf4bcf1e106d7b2bb3ab16238d71a98670294a7e1b4bc5f71e207a8186af260393340b5b30e1de4b7b6b30ed873307090ba08",
          "sha256": "f17624430f5b402d7bc7f65ef6c0cb4cdc41d4bc43cc56ac68354c839378947d",
          "sha1": "3425e12d267e7d542d90dc4667c46027611cc662",
          "md5": "ce093c268a22f93befa6a85055d7b697"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.1.aar",
          "url": "livekit-android-2.23.2.1.aar",
          "size": 4019288,
          "sha512": "4deede631d567394736a827e58faf4bcf1e106d7b2bb3ab16238d71a98670294a7e1b4bc5f71e207a8186af260393340b5b30e1de4b7b6b30ed873307090ba08",
          "sha256": "f17624430f5b402d7bc7f65ef6c0cb4cdc41d4bc43cc56ac68354c839378947d",
          "sha1": "3425e12d267e7d542d90dc4667c46027611cc662",
          "md5": "ce093c268a22f93befa6a85055d7b697"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2.1-sources.jar",
          "url": "livekit-android-2.23.2.1-sources.jar",
          "size": 1005248,
          "sha512": "ffe7ff56f943250dc1d3224765e6f50ac13349f364d06a250f81a1f421f3707cdce3275a790692be451e7acc04d7dd0580291e166f60b7a69e0dc88e170859d6",
          "sha256": "ce8e8764e2ea015c275365a98d2dfa6137a6463c5ad324f16462e88a494ce0f4",
          "sha1": "c9e6f989a2b9673ebbec10945ba9b505ce210702",
          "md5": "3e4ac72dadc0886d2596f4cb34c61b9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2.1-javadoc.jar",
          "url": "livekit-android-2.23.2.1-javadoc.jar",
          "size": 7458751,
          "sha512": "04f1be083be3c0112e364cce9782e24282e106884fc143c217eee2012f1f00a3e6ef76df6f06af9931025eaf6fc6ee1610c80102c631d76e82da7ce5bcca30c1",
          "sha256": "e83e3f85ce7f2066aa97cd408c965062103b519ad87bfe9b96510b76d358ebb5",
          "sha1": "42af182bee41081cefd3e91ac5f96c86b324ad6e",
          "md5": "5414939ddd5eed9461967f4f677a4e31"
        }
      ]
    }
  ]
}
