{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.22.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.4.aar",
          "url": "livekit-android-2.22.0.4.aar",
          "size": 3939862,
          "sha512": "f40ee99607adcb4e4d1abf52be2da157d5668843920f6aa36e7163c5162c280af994f9a2fc1a7625d6069a7c13a3f3da34dcf98bf8c14a0522d33ecee88ee4cc",
          "sha256": "9eb6dc7bda9fc120bfb1e9c6cf81f0e510eb612ee1f804498dbbd074b3021f8e",
          "sha1": "c91b5981e269416cbfd8b78b56f6763fbdf0a178",
          "md5": "fd813f3a5343dfa25730670cd921a8ab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.12"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.22.0.4.aar",
          "url": "livekit-android-2.22.0.4.aar",
          "size": 3939862,
          "sha512": "f40ee99607adcb4e4d1abf52be2da157d5668843920f6aa36e7163c5162c280af994f9a2fc1a7625d6069a7c13a3f3da34dcf98bf8c14a0522d33ecee88ee4cc",
          "sha256": "9eb6dc7bda9fc120bfb1e9c6cf81f0e510eb612ee1f804498dbbd074b3021f8e",
          "sha1": "c91b5981e269416cbfd8b78b56f6763fbdf0a178",
          "md5": "fd813f3a5343dfa25730670cd921a8ab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0.4-sources.jar",
          "url": "livekit-android-2.22.0.4-sources.jar",
          "size": 1000276,
          "sha512": "a2a13885031aa3dd5a057973d2415f322603dd65c1713687b8d2d687c796394bb6844a78013ab57f28c2d31ad690640c7919064db9ba509dedd7afc955615cf3",
          "sha256": "4a93fa0593c220a4c042d019336b07aa95942973bc0ced52378cc64a501292e2",
          "sha1": "fe388aa8b6e5652a56195c64b7fa5d4276ca7837",
          "md5": "e097bdfd3a5610e0beeac65720c35e9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.22.0.4-javadoc.jar",
          "url": "livekit-android-2.22.0.4-javadoc.jar",
          "size": 7448174,
          "sha512": "6ca0e9d76970dc660b70be1182ca321009683c08ed3fe4088c114cf6e49b0e5a66b732daf1f896bc2471bab38592e21c35195702f8935b8ebad7b313a4691b54",
          "sha256": "9457155f52669b7e108764999471c1b44cd92df013dbdd9ffb642f1967362663",
          "sha1": "a63cc56c79d77903e6cd086c644bda82787b8470",
          "md5": "bb7e5d7ba5d411c47e7a6a63ba6b8772"
        }
      ]
    }
  ]
}
