{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.4.aar",
          "url": "livekit-android-2.23.2.4.aar",
          "size": 4030322,
          "sha512": "8030a0e011eeb9c30d2aef3f0bccd711f505c16fd0eff9d27379bacd935ba72fa848ebb0f21f995a4bdd41ffe9e228cf7c6f6bd34d5b3b459ba53c545bb334fd",
          "sha256": "dcf0d3cf812a9892669a9355085945b9e634ca159e7bda3d7f40ae4c6711a36d",
          "sha1": "2f160e40e5c7db973065d354ea6f6a7baf4ded9a",
          "md5": "b20b4bc96da8fcf6fd217d19dd854aec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.2.4.aar",
          "url": "livekit-android-2.23.2.4.aar",
          "size": 4030322,
          "sha512": "8030a0e011eeb9c30d2aef3f0bccd711f505c16fd0eff9d27379bacd935ba72fa848ebb0f21f995a4bdd41ffe9e228cf7c6f6bd34d5b3b459ba53c545bb334fd",
          "sha256": "dcf0d3cf812a9892669a9355085945b9e634ca159e7bda3d7f40ae4c6711a36d",
          "sha1": "2f160e40e5c7db973065d354ea6f6a7baf4ded9a",
          "md5": "b20b4bc96da8fcf6fd217d19dd854aec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2.4-sources.jar",
          "url": "livekit-android-2.23.2.4-sources.jar",
          "size": 1007413,
          "sha512": "6788ede129172ca0a58f172b1d8d6bb9d35f88f37e42c5833045eaefd0363c3331e0d8ba02309ef9c812543ccda380bb074becc42981cf88ec84522e85921473",
          "sha256": "985fe0c4f5f5007644978e937299615f387b13a1ba54b6b69dbecc017b52d8db",
          "sha1": "c3d90dc89252363b8c1a421be532d82410af42ed",
          "md5": "609f3e46c38ceff7869e436203f41ebc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.2.4-javadoc.jar",
          "url": "livekit-android-2.23.2.4-javadoc.jar",
          "size": 7473225,
          "sha512": "916ac6c7672719ba16f49f745d992bd9606e4ff6d63d95911cc480ec3d61a6b54c5a2dcd4f75188efb2f4a0f4008aa9235860665a2bf2c59a0d124311d6a7c72",
          "sha256": "9f01cc2338369382e21ad5248a564b7bb6f5e3339c6b6e0912e580fea1ca3149",
          "sha1": "a98f9e1b4052f311c75c98c18cfcdf72ea2a02b9",
          "md5": "3f6da176fe7b5f31321db6c60304d8df"
        }
      ]
    }
  ]
}
