{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.23.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.7.aar",
          "url": "livekit-android-2.23.5.7.aar",
          "size": 4058127,
          "sha512": "f7a03b9a180f324d8d856e603383238384f9943e15f0b70d92a09487c00ef6df2c86ddf53c7f79c2666709b4decce650a829471a613bb71e087398a8ca5447b5",
          "sha256": "49ea9f4503286b41ac8b95cdb9ba9e1b692d052dbc1ecf171155cff2c4db7ee9",
          "sha1": "04b057066bbbc786780438928455e89ab8937e74",
          "md5": "4009057ef283a142f44c4da98f9fcfb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.23.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.23.5.7.aar",
          "url": "livekit-android-2.23.5.7.aar",
          "size": 4058127,
          "sha512": "f7a03b9a180f324d8d856e603383238384f9943e15f0b70d92a09487c00ef6df2c86ddf53c7f79c2666709b4decce650a829471a613bb71e087398a8ca5447b5",
          "sha256": "49ea9f4503286b41ac8b95cdb9ba9e1b692d052dbc1ecf171155cff2c4db7ee9",
          "sha1": "04b057066bbbc786780438928455e89ab8937e74",
          "md5": "4009057ef283a142f44c4da98f9fcfb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.7-sources.jar",
          "url": "livekit-android-2.23.5.7-sources.jar",
          "size": 1017616,
          "sha512": "dfd4f6abca1584dfc587d10da43d2899457184d33029a60c5db8014bb164f0f382c62a475e0a9bca143e924345942411d09d14dc86b6f7ba6552ca7c917430ec",
          "sha256": "3771c983e54da84bbd37cc8c604d5fd5bb8f59325b29e4a13aeab3a530e7698c",
          "sha1": "8558ff14fd39ea58a43a491d6783612c17ed5b85",
          "md5": "1654c3521d5feceb65cd76a88a4507e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.23.5.7-javadoc.jar",
          "url": "livekit-android-2.23.5.7-javadoc.jar",
          "size": 7475133,
          "sha512": "d97426bda420ee3091a844933fc34c32b246732aa1df088d3982bbff7a741f8f8c8487d43332e4144a72dc4eda1301cbad8d5b132e3f2eb56a84fe9ddd351ce8",
          "sha256": "8968ee70492573d72802d42adec097a19b2e649584b39f51add883c4fa524c5d",
          "sha1": "1c640f94bc0b25130fb6283595952ea00e7d5525",
          "md5": "49d0335c4f58781e123472bb71a8f400"
        }
      ]
    }
  ]
}
