{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.24.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.13.aar",
          "url": "livekit-android-2.24.1.13.aar",
          "size": 4141574,
          "sha512": "5ce03c1b0fda01dc18bb76264dfab5fe494726aae3de4cb639b00ebf86cf912a7563f7729a51e1a048cf1897f1b907f36a680357c192e6556b231c4b344e672b",
          "sha256": "93aa15481db75d1f43d0264ee1a132e0b46cee9fa81b9de75773a0c33bcbfb99",
          "sha1": "ff2e1daf89f908af692eaf9e8571d7f4a835f14c",
          "md5": "e0476f7d141d644488e400cffa70f99e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.24.1.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.13.aar",
          "url": "livekit-android-2.24.1.13.aar",
          "size": 4141574,
          "sha512": "5ce03c1b0fda01dc18bb76264dfab5fe494726aae3de4cb639b00ebf86cf912a7563f7729a51e1a048cf1897f1b907f36a680357c192e6556b231c4b344e672b",
          "sha256": "93aa15481db75d1f43d0264ee1a132e0b46cee9fa81b9de75773a0c33bcbfb99",
          "sha1": "ff2e1daf89f908af692eaf9e8571d7f4a835f14c",
          "md5": "e0476f7d141d644488e400cffa70f99e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.13-sources.jar",
          "url": "livekit-android-2.24.1.13-sources.jar",
          "size": 1036364,
          "sha512": "fe41d52f2bafe5ee11a48897a366908fc9f93dcc9d014f38c5698d2558c5d7c4f5dbeeab18923ddbbbad38c8eed625a3d5fa998594dadf0e9088f5435ed47185",
          "sha256": "37e28dfa3602a6b3dbe471a56b9e8903fc4682b7fbe175b218e6237eb6308a86",
          "sha1": "a6c234ac6d031f3ef7b69acfbbb678c89ffffe29",
          "md5": "1ce0bfc40b620d033292c7c6339bf29a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.13-javadoc.jar",
          "url": "livekit-android-2.24.1.13-javadoc.jar",
          "size": 7509976,
          "sha512": "36260914c4733acef5d730868496e4755fa51b68a071149addf408ae70bc1765639f1c6509d092155838f41647af5b92b85b52d5f5b952d89b389b20bf45b2eb",
          "sha256": "1f86f82ce0e4910244caf552d819e14f30565919a84355d1eee967866ce77587",
          "sha1": "23c2f455f3a23d7d4d1c1033f8840745387028aa",
          "md5": "f0d2ad863e624a46a6e528285cf1037e"
        }
      ]
    }
  ]
}
