{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.13.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.4.aar",
          "url": "livekit-android-camerax-2.13.1.4.aar",
          "size": 41060,
          "sha512": "33fdd40932930fa551f865c1429576b5300e336b5044116dac1cb7762ace2e67fba00eca1147d9ed8e3c512bf3d821922dc6b9026ef877c46386a35566cef3c8",
          "sha256": "52ba1e8e7a30ae631cefe6dd663ba9a002039cca9a65db3ffdc64ef1f3c62631",
          "sha1": "577336e80ed3152bb92073c90cdf7f33aaf5dca0",
          "md5": "122cf374c8b42242e518a75b9254afa5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.13.1.4"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.4.aar",
          "url": "livekit-android-camerax-2.13.1.4.aar",
          "size": 41060,
          "sha512": "33fdd40932930fa551f865c1429576b5300e336b5044116dac1cb7762ace2e67fba00eca1147d9ed8e3c512bf3d821922dc6b9026ef877c46386a35566cef3c8",
          "sha256": "52ba1e8e7a30ae631cefe6dd663ba9a002039cca9a65db3ffdc64ef1f3c62631",
          "sha1": "577336e80ed3152bb92073c90cdf7f33aaf5dca0",
          "md5": "122cf374c8b42242e518a75b9254afa5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.4-sources.jar",
          "url": "livekit-android-camerax-2.13.1.4-sources.jar",
          "size": 21733,
          "sha512": "752e3369d79c198e335859e9d886a7a3726ab8ef2d1b198f019e571b3d7d9abe89fd137295f354005f02b11635d4636ab3a24a2c4c125c62e6d041017e68a77e",
          "sha256": "ce95d94abc7136fafc7256b0d7936802039b0f100c64c3fa147939a2ac6065de",
          "sha1": "84993b47535d8f41d644e389543a6d1de4753fa3",
          "md5": "3695f3492b086eb267300c03ef4061dd"
        }
      ]
    }
  ]
}
