{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.20.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.4.aar",
          "url": "livekit-android-2.20.3.4.aar",
          "size": 3616965,
          "sha512": "a35d9eb9cece13e6e242b9ee775d2214456d10ff7e6ac61ee63e5cfe59cdc587e13c6994b06749ef855cb8b18194b3dd5726b246c49dbf368dc5a48b7ee266c0",
          "sha256": "3143185fde211815dd14d56864bef067330123fedcb0e0811ece0738b7dad2c8",
          "sha1": "4e2ee52c319512b4fca9a1c2dcd2b962d21787e5",
          "md5": "7f7ddb5baf60a3f925a16c3a4072077d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.11"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.20.3.4.aar",
          "url": "livekit-android-2.20.3.4.aar",
          "size": 3616965,
          "sha512": "a35d9eb9cece13e6e242b9ee775d2214456d10ff7e6ac61ee63e5cfe59cdc587e13c6994b06749ef855cb8b18194b3dd5726b246c49dbf368dc5a48b7ee266c0",
          "sha256": "3143185fde211815dd14d56864bef067330123fedcb0e0811ece0738b7dad2c8",
          "sha1": "4e2ee52c319512b4fca9a1c2dcd2b962d21787e5",
          "md5": "7f7ddb5baf60a3f925a16c3a4072077d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.4-sources.jar",
          "url": "livekit-android-2.20.3.4-sources.jar",
          "size": 921616,
          "sha512": "63633fcc6bc08d706dafde0d4f4458458c86465a4b414ed4fb03b747ea737288e173a9b7971a67d2ebaffbd58c39b1bc6816c496e04860fa3391a6a9400b89bb",
          "sha256": "9670e980da7680a3966707d4b7f61d028e5ac4d16b3541f72a20d08d2a19d54c",
          "sha1": "4a0587a0e9dbabd4fce5eff5bab6652c85050433",
          "md5": "e0abadad6faeef0c2fe27537db1a794a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.20.3.4-javadoc.jar",
          "url": "livekit-android-2.20.3.4-javadoc.jar",
          "size": 6839396,
          "sha512": "e2e4dbbaaa87cba6a849e4f6d06a10c0477c5e29245aee7f701fd4c04fba6ddeeb0c721bb3a0de2042860e48f846d7ef580ba143cd9f47b75b98cb665bd97555",
          "sha256": "85d1936744cd5d131886db1a7944809487ab02eb0d7cd6a80df24a0b448728fb",
          "sha1": "75492af3a7c7cbf4bf022c5ec88f1560ce91cc8c",
          "md5": "b75418b2b123f265cc91f7d2d9a21c82"
        }
      ]
    }
  ]
}
