{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.13.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1-SNAPSHOT.aar",
          "url": "livekit-android-2.13.1-SNAPSHOT.aar",
          "size": 2922406,
          "sha512": "16badd71f08132a09e5b6db6a59ad10419f6a64a83c824295b478934fd855dae562dc22deb7c1d7da1be6bb309a845fb944a35af61aa293cd7a76e212740ddd8",
          "sha256": "43edbe4d85e0e55b626f9b7ed7d0c0f45c6605561dc2fb06d577cbe70e51fa76",
          "sha1": "4ef785335c0f2bb54ea0f5cb40d5750a0af60bb0",
          "md5": "24f88ecb2aee09a440f8ec345e567dec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.13.1-SNAPSHOT.aar",
          "url": "livekit-android-2.13.1-SNAPSHOT.aar",
          "size": 2922406,
          "sha512": "16badd71f08132a09e5b6db6a59ad10419f6a64a83c824295b478934fd855dae562dc22deb7c1d7da1be6bb309a845fb944a35af61aa293cd7a76e212740ddd8",
          "sha256": "43edbe4d85e0e55b626f9b7ed7d0c0f45c6605561dc2fb06d577cbe70e51fa76",
          "sha1": "4ef785335c0f2bb54ea0f5cb40d5750a0af60bb0",
          "md5": "24f88ecb2aee09a440f8ec345e567dec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1-SNAPSHOT-sources.jar",
          "url": "livekit-android-2.13.1-SNAPSHOT-sources.jar",
          "size": 778303,
          "sha512": "9bc2d92e0c088668be6f406c637ca23c42814350d9d649f3fdba683421709cab06cc2e8917fb0cab32b85ab17c505c86257df2d6e697d997e200d07abd324f2d",
          "sha256": "86d00758006779439c4d57e6c3d4ef4d908167d4a69cdd4ea130cc26c1526d37",
          "sha1": "448c07505ea178bd84b85664f8b1a7f6ff993e4a",
          "md5": "636682df5dc3e932326627e749036903"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.13.1-SNAPSHOT-javadoc.jar",
          "url": "livekit-android-2.13.1-SNAPSHOT-javadoc.jar",
          "size": 5765462,
          "sha512": "79a3e662b9f171f6dc6aa219ba13fcf94ad2d59c943236c2122a2989fb3c34b59cb0bb03167f4e3ac2ac0c959dab69c1f87c450a383227c8253f2b98c66c1cd1",
          "sha256": "3119afd69dbbf3578b9cfdee4e335883da344c0a823ee81f3edd8b60da989568",
          "sha1": "78109a5f6f4b3eef6d308c7360a72fa112401509",
          "md5": "3b846d106dfd46f89e8a6a4de758418c"
        }
      ]
    }
  ]
}
