{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.18.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.4.aar",
          "url": "livekit-android-2.18.3.4.aar",
          "size": 3410624,
          "sha512": "ff59315c2673cc0a3159eccfd20bd205caa707316246412d93ea5f182955e637c67e6657fcf55ca0d2e3c267ffeb238ebc8b85d78cc69411c3f367e36d838422",
          "sha256": "d541938db077be76f03b3a45dcf798bd99858b74b33f925836d956d1bbdce720",
          "sha1": "c01fc590ccb3188a2110d42ca23b90376ad74c81",
          "md5": "a489b5571ac9fbd05229dbf49db39ca0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "125.6422.07"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.18.3.4.aar",
          "url": "livekit-android-2.18.3.4.aar",
          "size": 3410624,
          "sha512": "ff59315c2673cc0a3159eccfd20bd205caa707316246412d93ea5f182955e637c67e6657fcf55ca0d2e3c267ffeb238ebc8b85d78cc69411c3f367e36d838422",
          "sha256": "d541938db077be76f03b3a45dcf798bd99858b74b33f925836d956d1bbdce720",
          "sha1": "c01fc590ccb3188a2110d42ca23b90376ad74c81",
          "md5": "a489b5571ac9fbd05229dbf49db39ca0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3.4-sources.jar",
          "url": "livekit-android-2.18.3.4-sources.jar",
          "size": 872874,
          "sha512": "5401fa08a52e151ffef249f56184665ed3588211dc32707940f8526560d6bfe69a4bd3113ba6e41bb80975ad897d13aa73d4e6780c4c7bea550ce5f991d2e23d",
          "sha256": "273e8044b234dae1bac5a0bfd0487251172ecc6d2a03b5b2a1c609a02b2b52c9",
          "sha1": "7a5886654b4c0645346b8e5f65d57a87d2db0551",
          "md5": "e76950916c4b5d7c7f730b8974d6fcb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.18.3.4-javadoc.jar",
          "url": "livekit-android-2.18.3.4-javadoc.jar",
          "size": 6527572,
          "sha512": "7f6ebd4b82d3366fac4252fa9b6f5913995f7f32f78e91ec098bf74d243c170a1b49392a6f6a2d0d2177d8978d59b53f6e48964388e756c6714b19001f6f401f",
          "sha256": "e60977a6d5539dbd0ff0dee5996bd8ded256a528d021585a82ce2b5f9e5fb3e7",
          "sha1": "742f6abe2eb7eed71a93ee2ee5e85b2c91e96ca7",
          "md5": "c4ef8fd54137c1de98ffac38e3ca065a"
        }
      ]
    }
  ]
}
