{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "audioswitch",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "audioswitch-1.2.2.aar",
          "url": "audioswitch-1.2.2.aar",
          "size": 101362,
          "sha512": "e1a0ef9ff7b33ffed0b5b09d56131a8c36cd8017943ddb274b6de111f1157fdb6c7ce40a7b5932c30c0c8c1fc79a9daffec1ec174a117883632d661559545f9b",
          "sha256": "ae1255f99a6f96bf40e66eae4f94579cc59358be3fcd05efce44698a7d9a6aa8",
          "sha1": "6e2e309413ff08470c92a397f6efb86856f7eb08",
          "md5": "01d73af7aadcb631866222911d4b4230"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "audioswitch-1.2.2.aar",
          "url": "audioswitch-1.2.2.aar",
          "size": 101362,
          "sha512": "e1a0ef9ff7b33ffed0b5b09d56131a8c36cd8017943ddb274b6de111f1157fdb6c7ce40a7b5932c30c0c8c1fc79a9daffec1ec174a117883632d661559545f9b",
          "sha256": "ae1255f99a6f96bf40e66eae4f94579cc59358be3fcd05efce44698a7d9a6aa8",
          "sha1": "6e2e309413ff08470c92a397f6efb86856f7eb08",
          "md5": "01d73af7aadcb631866222911d4b4230"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "audioswitch-1.2.2-sources.jar",
          "url": "audioswitch-1.2.2-sources.jar",
          "size": 56125,
          "sha512": "e0c07c384417518616c62fb6cad0818da88d5dd497ddf352f4f3ce6282e9049777c42960f520b4f441c813c963f84c8f47f58d952f677ee6accdf1c8d1525518",
          "sha256": "b81f3b1ded34f7a3fa22d79ba3dc133a72d018f984fb1d4487c30bb9b9c08e61",
          "sha1": "5d0f39b4ebe12d04c7f361e9b4332a5ba5d15caf",
          "md5": "e9c9c4ef6981131b25aa1ea6d6991354"
        }
      ]
    }
  ]
}
