{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-track-processors",
    "version": "2.27.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.27.0.5.aar",
          "url": "livekit-android-track-processors-2.27.0.5.aar",
          "size": 41856,
          "sha512": "ea9845cbe9b399e55e48927beb39f6ddb79df2784e52b5b7085f414345064a6533f0c7063e68399c75600a41b7b1b9e7584448aa4491ad0b89d85312d77a3d2b",
          "sha256": "68fa10b999a3a7e10b5313edb712da9f46d1fb48e965037060b940f74da2d375",
          "sha1": "f42393d88905b36126feb704491a46b00b9354a8",
          "md5": "84d120f404ff88efa92476ac370fe8fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.27.0.5"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android-camerax",
          "version": {
            "requires": "2.27.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "segmentation-selfie",
          "version": {
            "requires": "16.0.0-beta6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.27.0.5.aar",
          "url": "livekit-android-track-processors-2.27.0.5.aar",
          "size": 41856,
          "sha512": "ea9845cbe9b399e55e48927beb39f6ddb79df2784e52b5b7085f414345064a6533f0c7063e68399c75600a41b7b1b9e7584448aa4491ad0b89d85312d77a3d2b",
          "sha256": "68fa10b999a3a7e10b5313edb712da9f46d1fb48e965037060b940f74da2d375",
          "sha1": "f42393d88905b36126feb704491a46b00b9354a8",
          "md5": "84d120f404ff88efa92476ac370fe8fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-track-processors-2.27.0.5-sources.jar",
          "url": "livekit-android-track-processors-2.27.0.5-sources.jar",
          "size": 17076,
          "sha512": "95912e8560d56ec2c73ddf373c27915c20bea04aa17888735c7638df126380da747eae770a77c099966e3aedf969b891a54b5f126ab9e561a16d5b6abb1404da",
          "sha256": "9303c0bf395f5d88e566b3aefa9579e98b3428170f96ee1d0fec41e85bc70672",
          "sha1": "67c673637480ecffef32e1304729098183a70fcb",
          "md5": "ef0ec9f34ed9435975c6eb5e4e0ac5a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-track-processors-2.27.0.5-javadoc.jar",
          "url": "livekit-android-track-processors-2.27.0.5-javadoc.jar",
          "size": 294538,
          "sha512": "375bd420bf879ce1cfccc51149d929c449e38ce10ae2cbcb53f3c0d1a5e7233bcb39c19cc7612b8af8a9a849f36717d41f87b0c22981a3c645a26d17d846f24e",
          "sha256": "4a90763d78879a953b27527c266ffa5160b7b6d4da4e905026d3928594035f61",
          "sha1": "083343e9c8ba30125d23243dadc8ca889dba0e00",
          "md5": "d908d6a8069efb0ee11d6c752a45331f"
        }
      ]
    }
  ]
}
