{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-track-processors",
    "version": "2.23.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.23.1.1.aar",
          "url": "livekit-android-track-processors-2.23.1.1.aar",
          "size": 41450,
          "sha512": "c42ea6ab940cdf31e74f0340b7ca515cf7334ba01e327b185a6f280e6dbeb0b734214256027b3aa21962dc1e3373a628f0bd51517519a0fcd1c9ac429c27aecf",
          "sha256": "1f64e5a3321076062401804ff4920001df18404177a2b3eb97168b1def7f5bb2",
          "sha1": "f1d9cfaba75be0d1554a7644b12f53585f9668ba",
          "md5": "74d91cc16aa185b1c489294983581607"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.1.1"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android-camerax",
          "version": {
            "requires": "2.23.1.1"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "137.7151.05"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "segmentation-selfie",
          "version": {
            "requires": "16.0.0-beta6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-track-processors-2.23.1.1.aar",
          "url": "livekit-android-track-processors-2.23.1.1.aar",
          "size": 41450,
          "sha512": "c42ea6ab940cdf31e74f0340b7ca515cf7334ba01e327b185a6f280e6dbeb0b734214256027b3aa21962dc1e3373a628f0bd51517519a0fcd1c9ac429c27aecf",
          "sha256": "1f64e5a3321076062401804ff4920001df18404177a2b3eb97168b1def7f5bb2",
          "sha1": "f1d9cfaba75be0d1554a7644b12f53585f9668ba",
          "md5": "74d91cc16aa185b1c489294983581607"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "livekit-android-track-processors-2.23.1.1-sources.jar",
          "url": "livekit-android-track-processors-2.23.1.1-sources.jar",
          "size": 33141,
          "sha512": "ae03d5371c2672888b17fb79b685043a8d5c193fd56adf4c5d78afee542d136d3bfb458ff07fcc02de55de866fe60b4842cdab3c791e43392086bb9df61c5a06",
          "sha256": "f3f2bd90c62abca40abc026330f4c6d8da4bee3c956dce44dac19c445cd1b8b1",
          "sha1": "63f6331b1090ceb8e17b87fb827622a27629a0b9",
          "md5": "b7b5c87c519e0bea23584cd2641ee032"
        }
      ]
    }
  ]
}
