{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.27.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.7.aar",
          "url": "livekit-android-2.27.0.7.aar",
          "size": 2888099,
          "sha512": "2a0c5a9668cc8b590eb16ea1e0a6d88d0460f549193312049f9012eb96ce600ad346c811b342b9ef67f6e38c003867ddfa1111f5b078452e3012d8f528a99d36",
          "sha256": "09d4a7a24dadc9400399eca18c85745ee603a5437f6b588b7bb87912193eccf9",
          "sha1": "d1945908d2cdb167967969ef64575ae582c2da1f",
          "md5": "b8facc09328b3076c398ab39435e5b7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.27.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.7.aar",
          "url": "livekit-android-2.27.0.7.aar",
          "size": 2888099,
          "sha512": "2a0c5a9668cc8b590eb16ea1e0a6d88d0460f549193312049f9012eb96ce600ad346c811b342b9ef67f6e38c003867ddfa1111f5b078452e3012d8f528a99d36",
          "sha256": "09d4a7a24dadc9400399eca18c85745ee603a5437f6b588b7bb87912193eccf9",
          "sha1": "d1945908d2cdb167967969ef64575ae582c2da1f",
          "md5": "b8facc09328b3076c398ab39435e5b7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.7-sources.jar",
          "url": "livekit-android-2.27.0.7-sources.jar",
          "size": 647093,
          "sha512": "5ccb1fd6e1ff141811ccd6b5673dbdebc0f77a17d6caea1e3380fa7564714a820e0606513a28880c3a064e97d122d2273edf44ed833fbb0776f622be76fc8488",
          "sha256": "fbb983788ba9ad6cdeb7028aee5b509f39653992354286ca58402147050fd980",
          "sha1": "4f3dbd2dccf3b41fb036a4b92454829bea321071",
          "md5": "bd5dd05404f2f21429e20dae26cf40bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.7-javadoc.jar",
          "url": "livekit-android-2.27.0.7-javadoc.jar",
          "size": 4127445,
          "sha512": "0e335536606a44042a06579926c73d8c5a9e2f1ce4d3ce1874739b514fb6665a6dadcbf0ed5c404d22f55187dff8d3edf4e9495c10a09937f8939b91557d8b42",
          "sha256": "e533513820f66005a179b3bcb9d3e48cf61ca584d9b1846dd7fe83c7a78a7201",
          "sha1": "a358d40b0a0463be2ec942c7a3bc06c25c2a0d11",
          "md5": "376957a93f08b50c3619d78ba5cd2966"
        }
      ]
    }
  ]
}
