{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android-camerax",
    "version": "2.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.aar",
          "url": "livekit-android-camerax-2.13.1.aar",
          "size": 40875,
          "sha512": "a6c56d8f51bd26f3e034114a0ab3864c688e5f88da7ff0e0594b58950e674d9c6dcc83c96fc098b3e5ddb6ff4f71ef942aafd7156df3c9e8b15a035adbb4dc37",
          "sha256": "41f67a875c5207182f8bbcb505373fb76e8031cb5df3a2b9ba64c9632f8db33a",
          "sha1": "12e1733fd2c3cf669ef283d2c4ae63f5cbb5a631",
          "md5": "6f41de54b6450a3e21078936249f0169"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "livekit-android",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "timberkt",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1.aar",
          "url": "livekit-android-camerax-2.13.1.aar",
          "size": 40875,
          "sha512": "a6c56d8f51bd26f3e034114a0ab3864c688e5f88da7ff0e0594b58950e674d9c6dcc83c96fc098b3e5ddb6ff4f71ef942aafd7156df3c9e8b15a035adbb4dc37",
          "sha256": "41f67a875c5207182f8bbcb505373fb76e8031cb5df3a2b9ba64c9632f8db33a",
          "sha1": "12e1733fd2c3cf669ef283d2c4ae63f5cbb5a631",
          "md5": "6f41de54b6450a3e21078936249f0169"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "livekit-android-camerax-2.13.1-sources.jar",
          "url": "livekit-android-camerax-2.13.1-sources.jar",
          "size": 21723,
          "sha512": "41b200eac29bafbd57e2c939ccdee3e67789fff7cd9ae8cfcc2016f25e12592acabb50f35911edb600a685660192e655785d042bc116856964dbef3da9556d20",
          "sha256": "800e937d71122f2bc5efeba4db10fcd634bf8cc8759bdda9e9f541e25e659f07",
          "sha1": "0fae50d51c0e75b9759e8d43e7a9067ee0c6df37",
          "md5": "39e04bfb6fe3ef45daa683cbe724b875"
        }
      ]
    }
  ]
}
