{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.27.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.4.aar",
          "url": "livekit-android-2.27.0.4.aar",
          "size": 2888208,
          "sha512": "e82182db2288fa215d3f0ddcd220b948201dc0dd9c1e717ab24f787871cf2611da430c1f8b3476bfb0373f0b4e45aa2ceeec2b6cc4f1cdd3f3029ddab35b8a6f",
          "sha256": "69b1b720d34afcac87ce1a24785946daee781243e513e08840d29419e620b102",
          "sha1": "a5e97ea42364bcf2a602cc44731cfced1d1b6e0e",
          "md5": "a3afa1570606be03ed23c06428fa7750"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.27.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.09"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.27.0.4.aar",
          "url": "livekit-android-2.27.0.4.aar",
          "size": 2888208,
          "sha512": "e82182db2288fa215d3f0ddcd220b948201dc0dd9c1e717ab24f787871cf2611da430c1f8b3476bfb0373f0b4e45aa2ceeec2b6cc4f1cdd3f3029ddab35b8a6f",
          "sha256": "69b1b720d34afcac87ce1a24785946daee781243e513e08840d29419e620b102",
          "sha1": "a5e97ea42364bcf2a602cc44731cfced1d1b6e0e",
          "md5": "a3afa1570606be03ed23c06428fa7750"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.4-sources.jar",
          "url": "livekit-android-2.27.0.4-sources.jar",
          "size": 646941,
          "sha512": "d7c75d8da720a5daf8073df61b25de6fbcee038d2f60437ab580c55632e37eccbd8939d833e859828c5be710e5217e4b207b849eaac1b282d9d7ccd56a626647",
          "sha256": "bc30ca0b4ca264503c88786dddbfbd50978450a6236ea5d4e2937e2412f0bd20",
          "sha1": "78693ba4238b68af524e06699fbeee7fc8ca317f",
          "md5": "9d9ca3b8972557f4c5f448e9298d11ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.27.0.4-javadoc.jar",
          "url": "livekit-android-2.27.0.4-javadoc.jar",
          "size": 4127315,
          "sha512": "a2189d6fc684ef61efddbb4d12859ae820de0597872fbfca6980e8189ec0753be32dd20a2240f775aa71bb17e28fec64eff97cf5f4ded75106aa344c8b31129f",
          "sha256": "772f231f14aabc2ce8dea08dd542dd3fccc02084b948067c74d5ee68d15483f1",
          "sha1": "d27507874b2de65450cb8fe49c0adb7619001465",
          "md5": "33dba9f6625f5eb3878637e4113f5515"
        }
      ]
    }
  ]
}
