{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "livekit-android",
    "version": "2.24.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.16.aar",
          "url": "livekit-android-2.24.1.16.aar",
          "size": 4150031,
          "sha512": "4efe929a4709472d5419245fa327657fca2589b54118774fd9901e8ce3b25ae6360736a6b7675e56bd20307f43f7fc1d9f47151807fcf0c0b044f1153144115b",
          "sha256": "c493a2342486beb06109e5bb6b8f901291405fe8b91afbfe530356dc2c8ec24e",
          "sha1": "2a53676354e839f77a0e50ba99d16592af1d0528",
          "md5": "a7f0b3e525c358634233fb1debc3b2ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.difft.android.libraries",
          "module": "ttsignal",
          "version": {
            "requires": "2.24.1.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "javax.sip",
          "module": "android-jain-sip-ri",
          "version": {
            "requires": "1.3.0-91"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android-prefixed",
          "version": {
            "requires": "144.7559.01"
          }
        },
        {
          "group": "org.difft.android.libraries",
          "module": "audioswitch",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "livekit-android-2.24.1.16.aar",
          "url": "livekit-android-2.24.1.16.aar",
          "size": 4150031,
          "sha512": "4efe929a4709472d5419245fa327657fca2589b54118774fd9901e8ce3b25ae6360736a6b7675e56bd20307f43f7fc1d9f47151807fcf0c0b044f1153144115b",
          "sha256": "c493a2342486beb06109e5bb6b8f901291405fe8b91afbfe530356dc2c8ec24e",
          "sha1": "2a53676354e839f77a0e50ba99d16592af1d0528",
          "md5": "a7f0b3e525c358634233fb1debc3b2ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.16-sources.jar",
          "url": "livekit-android-2.24.1.16-sources.jar",
          "size": 1038931,
          "sha512": "3de9b7f1c6bbc890906dc13ddf8abd8f40fc10a4710c376e4c68eefe10b48a821faf4a3df0c01934a4ee216d81d25906ffca036703c7f893b8f6de6094626797",
          "sha256": "a7ec9bdb610a13b335f5f31c89d91c263113a6caf4feecb85f876a4da62ef64f",
          "sha1": "50cc1a0d9a9fc7fefaaa07586487b3fbcd797da4",
          "md5": "0116d3865e2640b72e2e7b611b755979"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit-android-2.24.1.16-javadoc.jar",
          "url": "livekit-android-2.24.1.16-javadoc.jar",
          "size": 7493759,
          "sha512": "8df3ab47ce4fea95cc3f84b72917f6ac256286f88f8d89846517a0485b940769f9145ab3e4052f5660e5bd93c4a9d4c62b71381c5de4765673eb5a32a3e6eb8e",
          "sha256": "4af6ae5464adcd50bc9d46e24e0051edabcdc25df1f20f62f045bf0c3e130d2d",
          "sha1": "735762e9fd711fd03c14baa560a8ecf8ab83bd20",
          "md5": "20bf0b6aabea9c167ee3758ae8563026"
        }
      ]
    }
  ]
}
