{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "rust-encryption-sdk",
    "version": "0.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "rust-encryption-sdk-0.1.3-SNAPSHOT.aar",
          "url": "rust-encryption-sdk-0.1.3-SNAPSHOT.aar",
          "size": 2602309,
          "sha512": "293344917abd6ed59f2e6ff8a6ee33353fde1db672180dd3008f62ebfad4000dee833cb51e5438f0a94b12b0b2684da15e7f9b03a5ea9f9bf5f99cfd85d1ce80",
          "sha256": "945b9e32f0fc14c3ba4fa0968a0e9720c4ccd793569892d4f77c1fc41362864b",
          "sha1": "5fcb1852ac0cddcf77776a427b404d68047676da",
          "md5": "47891d4d39d4a30d967ae0dc7cd54537"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "rust-encryption-sdk-0.1.3-SNAPSHOT.aar",
          "url": "rust-encryption-sdk-0.1.3-SNAPSHOT.aar",
          "size": 2602309,
          "sha512": "293344917abd6ed59f2e6ff8a6ee33353fde1db672180dd3008f62ebfad4000dee833cb51e5438f0a94b12b0b2684da15e7f9b03a5ea9f9bf5f99cfd85d1ce80",
          "sha256": "945b9e32f0fc14c3ba4fa0968a0e9720c4ccd793569892d4f77c1fc41362864b",
          "sha1": "5fcb1852ac0cddcf77776a427b404d68047676da",
          "md5": "47891d4d39d4a30d967ae0dc7cd54537"
        }
      ]
    }
  ]
}
