{
  "formatVersion": "1.1",
  "component": {
    "group": "org.difft.android.libraries",
    "module": "ttsignal",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ttsignal-1.0.3.aar",
          "url": "ttsignal-1.0.3.aar",
          "size": 2604218,
          "sha512": "512e850bca3356e22e2b61afee65c5180159e391aed87960eb1f6340ef511e055121fe2192f01be9081606678009c7cf23f989a31feaa2d88b5590ad1e108dd1",
          "sha256": "d8416a7ab78250bf8f437ac0cba15bd9d12e24ecaafb80ffffacd2c0a13ab433",
          "sha1": "49b7810abdb26d8b00cbf4e694c8dbab79a87907",
          "md5": "74ef152f4e52fd273c94f0ef074d15d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "ttsignal-1.0.3.aar",
          "url": "ttsignal-1.0.3.aar",
          "size": 2604218,
          "sha512": "512e850bca3356e22e2b61afee65c5180159e391aed87960eb1f6340ef511e055121fe2192f01be9081606678009c7cf23f989a31feaa2d88b5590ad1e108dd1",
          "sha256": "d8416a7ab78250bf8f437ac0cba15bd9d12e24ecaafb80ffffacd2c0a13ab433",
          "sha1": "49b7810abdb26d8b00cbf4e694c8dbab79a87907",
          "md5": "74ef152f4e52fd273c94f0ef074d15d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-1.0.3-sources.jar",
          "url": "ttsignal-1.0.3-sources.jar",
          "size": 5842,
          "sha512": "e5994df6cc765e6cb41bb3b124e476121e6e3d5a84110094043543b495a3ad62d7b95832572b29b425e89bd1f7bf5b6fd16afbb103ce50b68a7c22bf402ddc50",
          "sha256": "e77ef2444d05b2dbd9b6aa4c9fae633ffc91c17aa8bea60ba1969d3678a36855",
          "sha1": "b8fe9cb9200b0eb219194fd86207a4997871dee9",
          "md5": "39e79c233dccc775496c79a9e0915ad8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ttsignal-1.0.3-javadoc.jar",
          "url": "ttsignal-1.0.3-javadoc.jar",
          "size": 294425,
          "sha512": "59f68462882f4c3d8a9f950b494482add88520935a693fce254513f30368fd709b979c2db79cda6fdfdbdcf77239102dd534f5c79277bf4ae9bc3f49c2c4fe87",
          "sha256": "6892cf176b9ecd5717bfbf6a3246d0d0d777a9cdc169f14b1311a7a05f1340e6",
          "sha1": "bfc50ff71dd6beb2c7b989065434babb82e78c40",
          "md5": "ae16d0c86306f1c504a4cb3347dd89ab"
        }
      ]
    }
  ]
}
